### ISSUE TITLE
Some cards carried over to warlock quest fail to mention new effects

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#1]
Woof Woof Woof still just says "repeat next attack" when it ought to say "repeat next attack, but disable it next turn" since that's what it really does. Maybe have some "alternate description" field for every card that's used in the warlock quest if needed?

**Comment by ncrecc** [comment]
Oh yeah, same applies to freeze cards saying they "freeze 1 dice"

**Comment by ncrecc** [comment]
...but Grappling Hook is properly updated.

**Comment by TerryCavanagh** [comment]
Ok! I added alternate descriptions for all affected enemy equipment. This one should be done!
