### ISSUE TITLE
Cactus and Warlock show as white squares in the overworld/editor enemy selection

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#10]

**Comment by ncrecc** [comment]
They also show as white squares in the map! Guess they don't have any icons at all.

![](https://i.frogbox.es/loa)

**Comment by TerryCavanagh** [comment]
Fixed! 👍 
![cactuswarrior_01](https://user-images.githubusercontent.com/2874150/57828420-98231780-77ea-11e9-93e3-9b3d79b142db.png)
![warlock_02](https://user-images.githubusercontent.com/2874150/57828423-9b1e0800-77ea-11e9-8105-61b788024cc4.png)
