### ISSUE TITLE
You shouldn't be able to snap a shocked card

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#114]

**Comment by paceheart** [comment]
Also, it's currently messed up - if you do snap a shocked card, then despite the card still appearing to be shocked, if you put a dice in it to unshock it, the card will activate.

**Comment by TerryCavanagh** [comment]
This is fixed - I don't remember doing it, but if you snap a shocked card it just instantly unshocks it, which is a nice and generous solution here.
