### ISSUE TITLE
Buttons on enemy cards aren't handled very well visually

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#12]
Right now Shock? gives a random card an "unshock" button. If you shock an enemy's card, there's no animation for the enemy "pressing" the unshock button, and you can also press the enemy's unshock button yourself (to no effect).

**Comment by TerryCavanagh** [comment]
Am fairly happy with the slight weirdness of buttons appearing in contexts where pressing them does nothing! I don't think there's really very much to be gained from having a different appearance for this situation.
