### ISSUE TITLE
Crash in repeatlastaction

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#120]
```
I used Snap on Ruff Ruff Ruff while I had Fury?, both of them triggered, and 
I was left with 1 Fury. Then, I tried to use a Sour Candy and the game crashed. 
Didn't get a recording but got this error log https://pastebin.com/ZFEjbQsD
```

```
--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v0.4 beta (14th June) / 0.8.0 (mod API)
sess. ID:	dicey_dungeons_2019-06-14_21'11'12
started:	2019-06-14 21:11:12
--------------------------------------
crashed:	2019-06-14 21:20:12
duration:	00:08:59
error:		Null Object Reference
stack:
states.Combat.repeatlastaction (states/Combat.hx line 1383)
elements.Equipment.doequipmentaction (elements/Equipment.hx line 1984)
Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 501)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 579)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)
```

**Comment by lcenine** [comment]
Same thing happened here.

`--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v0.6 beta (28th June) / 0.10.0 (mod API)
sess. ID:	dicey_dungeons_2019-07-16_13'52'38
started:	2019-07-16 13:52:38
--------------------------------------
crashed:	2019-07-16 14:25:46
duration:	00:33:07
error:		Null Object Reference
stack:
states.Combat.repeatlastaction (states/Combat.hx line 1386)
elements.Equipment.doequipmentaction (elements/Equipment.hx line 2031)
Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 501)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 579)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)`

**Comment by TerryCavanagh** [comment]
I think this was due to a null object in repeatlastaction, which I remember fixing. Closing!
