### ISSUE TITLE
Concentration should probably use the green plus symbol in its description & status effect tooltip

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#135]
Currently it uses no symbol in its description, and the red heart symbol in its tooltip.

**Comment by TerryCavanagh** [comment]
Oh, this is deliberate :( Basically I really dislike having mismatched colours in equipment cards, so opted against having both the Magenta and Green icons on the same card. It's not ideal, but better than the alternative, I think.
