### ISSUE TITLE
combatboss sounds really staticky and distorted

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#137]
Maybe it always sounded like that? Maybe that's part of the effect? Dunno, but it sounds super weird now, especially 30 seconds in.

**Comment by TerryCavanagh** [comment]
I'm not sure what's going on here, I don't think this file has changed in a while!

Could you try finding the `.ogg` file in the steam folder (under `soundstuff\music\combat\combatboss.ogg`) and see if that sounds the same to you? Might be something to do with the way we're playing the music files, or maybe it's just that the sound sounds bad on your audio setup. Either way, both are probably fixable problems!

**Comment by ncrecc** [comment]
Huh, you're right - hasn't changed since March 4th. Although I'm listening to it in only the right stereo channel now (left earbud stopped working), so maybe it sounds fine with both channels active.
It sounds the same when listening to it outside of the game.

**Comment by TerryCavanagh** [comment]
I tried listening to this track with one earphone in, and yep, it definitely sounds a bit weird. I'm not sure if this is the sort of thing Niamh can do much about, but I'll mention it to her in case it's, like, a setting she can control.
