### ISSUE TITLE
Add lines to "must equal" equipment, like in earlier versions

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#138]
![](https://i.frogbox.es/lrz)

**Comment by TerryCavanagh** [comment]
Ok, that should be easily enough done!

**Comment by onetruepurple** [comment]
Silly idea: draw a + sign between the slots, and add an equal sign in front of the "must equal #" text.

**Comment by TerryCavanagh** [comment]
Ah, not going to do this now I think.
