### ISSUE TITLE
Vampire can die from Cursed? equipment

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#139]
https://streamable.com/hoi0n

**Comment by TerryCavanagh** [comment]
Looks like this is on parallel universe rules, after the "first" Vampire? health recovery. It's working as intended!

(...except for the innate being wrong and confusing, which is a separate issue  here: https://github.com/TerryCavanagh/diceydungeonsbeta/issues/121)
