### ISSUE TITLE
Make giveequipment() return the instance of the newly created Equipment

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#140]

**Comment by ncrecc** [comment]
This would be very useful, currently if you want to do something with/to an equipment spawned by giveequipment you have to manually mark all preexisting equipment as "already here" with some setvar, do giveequipment, then iterate through self.equipment for an equipment that doesn't have the "already here" mark (and then reset the "already here" mark for all equipment). This would be much faster.

**Comment by TerryCavanagh** [comment]
This is a good suggestion! Pretty sure it's mentioned on the main repo somewhere though.
