### ISSUE TITLE
The "keep going!" lines in Precious Egg cards are absent from Precious Egg+

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#142]
Intentional?
(While I'm talking about Precious Egg: perhaps Precious Egg@1 (and its upgraded version) could have "Almost there!" instead of "Keep going!"?)

**Comment by TerryCavanagh** [comment]
Fixed.

**Comment by TerryCavanagh** [comment]
(oh, actually, not fixed, but I think this is ok as is)
