### ISSUE TITLE
e.changeslots() is buggy with reusable items

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#144]
If you use `e.changeslots` on a reusable item, and the dice you put in doesn't fit in the item normally, then the dice gets spat out afterwards and you can drag it around.

For example, this item normally only takes 2s. After it gets its slots changed to take any dice, I put a 6 into it. 6 doesn't normally fit into it, which leaves me with a spare dice I can drag around.

![ezgif-3-160c66e515ad](https://user-images.githubusercontent.com/32357485/59637807-997b9300-914e-11e9-8eb6-c328778bfee2.gif)

You can see that when it fires, the normal slots (here a REQUIRE2 slot) show up.

**Comment by TerryCavanagh** [comment]
Ah, yep, changeslots() is pretty broken still, even after the Magician update. Planning a fix at some point, and I think this issue is covered in the big modding thread over on the main repo.
