### ISSUE TITLE
Losses not being recorded.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#147]
I just noticed that all my wins have been recorded (and continue to be recorded) but all my losses have been set to 0. On losing they do not get incremented.

Warrior I just lost a PU run but it is still showing no losses.

![losses](https://user-images.githubusercontent.com/40739964/59705677-db4b1e80-91cc-11e9-91df-dd005a7c0471.jpg)

**Comment by TerryCavanagh** [comment]
Fixed!
