### ISSUE TITLE
Jester - Enemy Moves Preview Shows Player Equipment If Clicked during Your Turn.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#148]
I can replicate this one in all Jester Episodes and the editor.

If you are playing as Jester and click on the preview button during your turn  as an attack item is animating toward the enemy you will see your own equipment.

![preview](https://user-images.githubusercontent.com/40739964/59713323-253c0080-91dd-11e9-83ba-e83696fc7b53.jpg)

Sometimes your equipment stays on the preview grid and you get soft locked because you cannot place any dice because all your playable  items  in the enemy preview preview grid.

![softlock_preview](https://user-images.githubusercontent.com/40739964/59713585-c32fcb00-91dd-11e9-8fc8-cad47b7986c9.jpg)

![softlock](https://user-images.githubusercontent.com/40739964/59713616-d347aa80-91dd-11e9-8f5b-424df5009e57.jpg)

**Comment by TerryCavanagh** [comment]
Fixed!
