### ISSUE TITLE
Witch Elimination Round Thoughts.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#149]
I am not awesome at Witch but I have won 4 times now and it should perhaps be a little harder.
 
I was wondering if the added difficulty (that's coming in 1.0!) could be a 50% chance of dice "ricocheting" back to damage Witch or healing the enemy. 

Often I found the last fight on a floor to be within just a few hp of winning or losing, as in I'm at 3 hp and the enemy is at 2 hp or we both have 2 hp.  Really close battles that might be more exciting if they were a little closer or had to be played a little differently.  Thrown dice definitely have had an impact in wins/losses and it being a unique Witch mechanic it would be nice to have it be instrumental in the Elimination Round as what could make or break a run.

**Comment by lcenine** [comment]
Perhaps giving enemies the "Sorceress" remix ability would be interesting.

**Comment by TerryCavanagh** [comment]
Haha, this is hilarious to read after launch 😄
