### ISSUE TITLE
Last Stand? is kind of mean

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#15]
Especially if your name is Jackeea and you used it on the first turn of battle! It would be a lot less cruel to say "survive for three turns ONLY" or something to that effect. It's like a Kaizo trap in card form.

**Comment by TerryCavanagh** [comment]
It is, but, I think the dot dot dot kind of has the same effect as the "ONLY" bit. I think this is fine! I'll ask the dicecord to weigh in, though!

**Comment by TerryCavanagh** [comment]
Yeah, I've thought it over, and I think I wanna keep it as is!
