### ISSUE TITLE
"music_floorN_songN" soundevents probably shouldn't be hardcoded

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#150]
If someone made an extra floor, they wouldn't hear the combat music even if they added a custom soundevent called "music_floor7_song1".
The AudioControl.hx file shows an error in the console:
```
AudioControl.hx:115: Event null does not exist
```

**Comment by ncrecc** [comment]
Fixed - those soundevents don't exist anymore
