### ISSUE TITLE
Parallel Universe description needs a rewrite

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#160]
![image](https://user-images.githubusercontent.com/2095534/59856051-6d425b00-9376-11e9-9767-76ddd23844b6.png)

**Comment by ncrecc** [comment]
You mean Elimination Round description?

**Comment by onetruepurple** [comment]
Umm, yes. Thanks for catching that.

**Comment by onetruepurple** [comment]
Resolved
