### ISSUE TITLE
Splitula's description glitches out once you attempt to upgrade it

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#167]
![image](https://user-images.githubusercontent.com/32357485/59947487-43b42d00-9465-11e9-97db-f8a30c2b3bce.png)

Should be fixable by setting the upgrade's description to `Flip a dice upside down[;]|duplicate the flipped dice|` - the "3 uses this turn" text is overwriting the second line.

**Comment by TerryCavanagh** [comment]
Fixed!
