### ISSUE TITLE
Dramatic Exit doesn't take Weaken? into consideration

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#169]
`if(1 + getstatusself(THORNS) >= target.hp){ self.maxhp+=2; attackself(-2); attack(1); } else { attack(1); }` is the current code for Dramatic Exit. While this will work for Thorns?, it wouldn't take into consideration Weaken? from a stolen card.

Consider changing the code to be `attack(1); if(target.hp <= 0){ self.maxhp +=2; attackself(-2);};` - do the attack, then check the target's health. This will futureproof it against any other "your attacks deal more damage"-like effects.

**Comment by TerryCavanagh** [comment]
Thanks! Fixed :)
