### ISSUE TITLE
Null Object Reference crash still persists

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#17]

**Comment by onetruepurple** [comment]
This one happened when attempting to continue a paused run:

![image](https://user-images.githubusercontent.com/2095534/57481071-95339e80-72a1-11e9-99dc-23f05135ab97.png)

**Comment by mrcdk** [comment]
hi! thanks for the report! 

We will need some more info for this one. Do you still have the `continuesave.json` file that triggers this error? it's located in `%APPDATA%\Terry Cavanagh Games\diceydungeons` 

If not, could you give us some more info so we can reproduce it? Like which character were you playing with and which episode, in which floor,...

Thanks!

**Comment by TerryCavanagh** [comment]
Fixed!
