### ISSUE TITLE
Items that curse in PU need changed descriptions

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#172]
Dire Wolf Howl, Laugh Track, etc have "(items might fail)" in their descriptions despite Curse working differently in PU

**Comment by mothbeanie** [comment]
perhaps (items might backfire)?

**Comment by onetruepurple** [comment]
Easier to just remove the line wholesale, since it predates status effects having tooltips.

**Comment by TerryCavanagh** [comment]
Yep - "items might backfire" is a very good suggestion, but the easier thing to do now is just remove the line, which isn't needed anymore now that tooltips are a thing.

**Comment by ncrecc** [comment]
Resolved with "(items might fail)" being removed
