### ISSUE TITLE
Witch and Thief skillcards break when reloading save

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#173]
If you:
* start a game as Witch
* exit to title 
* add a spell to your spell book in the editor
* return to the title
* reload your save
then your spellbook will no longer accept dice in that savefile (throw dice works fine, though). reloading your save (even after closing the game) has the spellbook still broken. starting a new game also gives you an unbroken skillcard

**Comment by ncrecc** [comment]
This seems to happen with reloading your save in general.

**Comment by mothbeanie** [comment]
![thief broken skillcard](https://user-images.githubusercontent.com/19874772/59972257-b940fb80-9540-11e9-895b-5c98ee0d937e.png)
update: this happens with thief too! i tested the other characters, but it didn't happen with them so i think it's just thief and witch

**Comment by TerryCavanagh** [comment]
Fixed.
