### ISSUE TITLE
Master Key and Knitting Needle upgrades say that they become more powerful, when in reality they become easier to play

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#177]
![image](https://user-images.githubusercontent.com/26709843/59964609-3d34bc80-951c-11e9-840d-fa0c80c46f03.png)
![image](https://user-images.githubusercontent.com/26709843/59964611-41f97080-951c-11e9-8139-9ff288afff9a.png)
Both of these items use `change_power` instead of `change_requirements`.

**Comment by TerryCavanagh** [comment]
Fixed!
