### ISSUE TITLE
Combat Spatula is not exempt from being disabled by burnt? dice, despite being a skillcard

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#18]
[12:25 PM] Jackeea: ...combat spatula undoes burn?
[12:25 PM] Jackeea: .........but gets disabled the next turn
[12:25 PM] codyfun123: sounds like an oversight
[12:25 PM] Jackeea: fUCK
[12:25 PM] codyfun123: or not

If skillcards can't be shocked or cursed, they probably shouldn't be deactivated by burnt dice.

(This is a 2-in-1 if you regard Combat Spatula not preserving burn status as a separate bug.)

**Comment by TerryCavanagh** [comment]
Gonna try a new behaviour here, where using burning dice on reusable equipment knocks it out for the rest of the turn, in addition to knocking it out next turn. It's a little harsh, but I think it feels like more of the "expected" behaviour.

As for applying to Combat Spatula: I'm torn here, but considering making Combat Roll act like regular equipment, susceptible to curse and shock. For now, though, I've just fixed the fire bug.
