### ISSUE TITLE
Fury? doesn't work with Elastic Heart (and presumably other Boomerang items)

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#19]
Used Fury? before using Elastic Heart, put a dice into it, the item activates... once, leaving me with the Fury status.

Edit: Both items are Unavailable next turn!

**Comment by TerryCavanagh** [comment]
Yep, this is due to me trying to use Boomerang here, which isn't really necessary. Just gonna disable that for the timebeing!
