### ISSUE TITLE
Died to a Super Rose, in the next game, a level 1 rose was labeled "Super Rose"

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#199]

**Comment by YinYin-Falcon** [comment]
Dug up the footage for that just to make sure:
https://youtu.be/lGz6TpEOOYE?t=575
(engaging the "super" level one rose at the time stamp - loss to the actual super before)

**Comment by TerryCavanagh** [comment]
Fixed!
