### ISSUE TITLE
Warrior is a still image in battles now

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#2]
Warrior doesn't do his idle animation anymore in the battle screen!

**Comment by TerryCavanagh** [comment]
Huh! So he doesn't!

(Referring to this animation:)
![image](https://user-images.githubusercontent.com/2874150/57507752-00817d00-7343-11e9-9582-40c7bad8f80e.png)

**Comment by TerryCavanagh** [comment]
Fixed!
