### ISSUE TITLE
Super RoboBot is a little odd

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#211]
they have 3 dice, but 4 plasma blasters. (maybe they should only have 3 plasma blasters, or maybe 3 plasma blasters and a pea shooter?)

**Comment by onetruepurple** [comment]
Presumably it's a safeguard against Shock and Weaken (which aren't uncommon effects on floor 2).

**Comment by TerryCavanagh** [comment]
I'm happy enough with Super Robobot's design as it currently is.
