### ISSUE TITLE
Poison? is completely ineffective against the Witch

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#213]
Any spell with a Poison? countdown can be just overwritten with another.

**Comment by YinYin-Falcon** [comment]
Not _completely_ ineffective, since that still requires a dice - but it makes the poison count itself meaningless.

I think all poison? cards should probably be locked into place until you clear them?
That would also mean no discarding or snapping them on the Jester.

**Comment by TerryCavanagh** [comment]
```
I think all poison? cards should probably be locked into place until you clear them?
```

Agreed!

**Comment by TerryCavanagh** [comment]
Ah, at this point I'm actually fairly ok with this behaviour as is.
