### ISSUE TITLE
Consider another design pass on Vampire

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#219]
Queen Bee and Scathach already have strong Shock based attacks, so there's an opportunity to explore something else with the Vampire.

Assuming it's important to keep Smog Cloud as part of his line up, either Blind or Confuse are good thematical fits.

**Comment by TerryCavanagh** [comment]
I think I wanna keep Confuse special for Warlock, but Blind could work (especially once I get around to that long overdue behaviour change)

**Comment by TerryCavanagh** [comment]
Vampire Blinds now. Blind just got a big buff, so I think this is a good direction.
