### ISSUE TITLE
Consider applying different colors to the parallel universe status effects

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#22]
I.e. cyan Dodge, pink Poison, purple Fury.

**Comment by TerryCavanagh** [comment]
I thought about this one a little bit (I considered changing icons too), and I think it's important to keep the connection between the original status effects. Having a colour change would just push the parallel universe status effects in the direction of being "new status effects", which I'd rather avoid.
