### ISSUE TITLE
Consider nerfing Divine Rod+

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#220]
PU Robot can trigger it almost too frequently.

**Comment by TerryCavanagh** [comment]
Have some plans set in motion here!

**Comment by onetruepurple** [comment]
Resolved in v0.6:

![image](https://user-images.githubusercontent.com/2095534/61065813-bbda9680-a404-11e9-9421-e8dfdf870c27.png)
