### ISSUE TITLE
"to do: using finders keepers in the editor with new level up screen"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#222]
![](https://cdn.discordapp.com/attachments/591227440144318464/592186092586008618/unknown.png)
How old is this error? "New level up screen" makes me suspect at least 0.16.

**Comment by ncrecc** [comment]
Similar todo error with completing a battle as Inventor and going to the gadget screen

**Comment by TerryCavanagh** [comment]
There's a duplicate of this on the main repo <3
