### ISSUE TITLE
Suggestion/Ideas: Silence for Robot and Jester

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#223]
for robot:
* only the calculate button is visible
or
* no jackpot
for jester:
* only the discard/snap button is visible (like multicard with less multi)
or
* can't discard/snap

**Comment by onetruepurple** [comment]
At the very least, their limit breaks should be also affected.

I like obscuring the Robot's counter.

**Comment by mothbeanie** [comment]
oh, yeah, limit breaks too! forgot to include that

**Comment by TerryCavanagh** [comment]
No longer planned! The suggestion here ended up being what I did for Robot Blind though :)
