### ISSUE TITLE
Resumed save won't allow dice placement. PU Witch.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#224]
Continued a PU Witch saved game.  First encountered an issue were dice could not be placed in the spell slots against Rose on Floor 1.  Wondered if it was a weird quirk with Rose so started a new game.

On new game start Rose was the first enemy. On round start  I saw the "tutorial" text on the spell book (which wasn't there the first time) . Dice were accepted without a problem.

On another continued save I encountered the issue  again on Floor 2 against Super Space Marine.

Edit: And again with Crystalina on Floor 4. Exiting DD and relaunching doesn't fix it.

https://drive.google.com/file/d/1ngwwAuY2vh1j_TxLtpK0teEgUi4rm9jn/view

Continuesave.json attached.

[continuesave.zip](https://github.com/TerryCavanagh/diceydungeonsbeta/files/3321185/continuesave.zip)

**Comment by TerryCavanagh** [comment]
This one is fixed!
