### ISSUE TITLE
Background sometimes overlaps Enemy Description

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#225]
Something a little weird with the z-index of the background and enemy. Descriptive text disappears below the "floor".

(lvl 2) is clipped off, e.g. on Super Space Marine. On enemy encounter animation the text continued to disappear behind the floor tile. 

![zindex](https://user-images.githubusercontent.com/40739964/60026187-23ed5680-9669-11e9-8c54-f77b07d4b661.jpg)

**Comment by TerryCavanagh** [comment]
Fixed!
