### ISSUE TITLE
Feature Request: Ability to Preview Upgrades When Getting Items

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#228]
The ability to preview an items upgraded version would be helpful.

Shops, the leveling up "choose a reward" interface and chests could all show a 'preview upgrade' option. 

The only mildly awkward thing is going to be presenting that with the Witch because there is already a "preview upgrade" check box... but that only affects items in the Spellbook.

**Comment by TerryCavanagh** [comment]
Not planning to implement this!
