### ISSUE TITLE
Winning a battle while Nail Bat is equipped causes the stats at the bottom of the screen to shake

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#23]
![](https://i.frogbox.es/lod)
Not a very good gif, just take my word for it.

**Comment by ncrecc** [comment]
Apparently because Nail Bat damages you as soon as the battle ends (but before level-up health refill I suppose).

**Comment by TerryCavanagh** [comment]
Fixed!
