### ISSUE TITLE
Suggestions: Battle UI

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#231]
The "Flee" button could use a "are you sure you want to flee?" prompt in case it accidentally gets clicked. you can also get a dice stuck if you place it too close to the "enemy moves" button, so maybe that could be moved near the flee button because dice are less likely to be put there. (ex, when "return the dice" items backfires with curse?, the dice appears at the top of the screen and might get stuck if youre not careful)

**Comment by TerryCavanagh** [comment]
Yay, this got implemented in a big panic for v1.1 after lots of people complained about it, haha. Sorry for not applying it sooner.
