### ISSUE TITLE
UI Overlap When Gold Appears in Combat

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#232]
This was fixed  [here](https://github.com/TerryCavanagh/diceydungeons.com/issues/755) but is back again in Witch PU.

![overlap](https://user-images.githubusercontent.com/40739964/60115151-481d6600-9743-11e9-8b4a-b4c10d6c7ef0.jpg)

**Comment by TerryCavanagh** [comment]
This is a pretty minor issue that honestly I'm happy to live with.
