### ISSUE TITLE
Sometimes cards disappear and reappear the next round.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#234]
Instead of them going translucent they disappear.

Managed to grab a screen cast of it happening. It doesn't happen in the same slot and it has happened with different equipment. 

https://drive.google.com/file/d/12PI0sKDYM5jlJU2E_t1cnlePN8WXcrcJ/view

**Comment by TerryCavanagh** [comment]
This one's still around in v1.9 and I don't know what causes it. Hoping to figure it out (there's a few issues about it on the main repo).
