### ISSUE TITLE
Blue, cyan, and brightcyan all show as the same color, as do white and gray

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#235]
Moved from https://github.com/TerryCavanagh/diceymodgeons/issues/2
With modgeons allowing you to select these colors for cards and showing them as identical same thing in the preview, this is a bit confusing.
(White and grey both show as the same color, just not as the same color blue, cyan, and brightcyan show as)

**Comment by onetruepurple** [comment]
I don't think I've seen cyan, blue, or white cards appear, ever. Must be some really old experiments that were never properly removed.

**Comment by mothbeanie** [comment]
In v0.10, silver cauldron used the white color:
![v010 silver cauldron](https://user-images.githubusercontent.com/19874772/60362965-1c92b980-9997-11e9-924a-88f1d6bd9861.png)
blue was never used, but i swear regular cyan was at some point

**Comment by TerryCavanagh** [comment]
I think this can be closed from the DD side, not sure if it's still an issue on the DM side!
