### ISSUE TITLE
Wooden Stake? damages anyone, not just Vampire

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#236]
Right now Wooden Stake? can be obtained with CfB Robot or Expect the Unexpected (if I recall correctly), and it clearly does not just damage Vampire. Either tweak the equipment so it fails if not used against that specific enemy (if that's possible) or just remove the "(to vampires)" line.

**Comment by TerryCavanagh** [comment]
No longer comes up! (it's excluded from random lists)
