### ISSUE TITLE
Losses not shown until episode is completed.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#237]
I just noticed that an uncompleted episode on the door has the episode name and incomplete. 

When the episode is beaten, the previous losses populate.

It would be nice to know how many times a run was attempted before I ever complete it. 

![cr](https://user-images.githubusercontent.com/40739964/60355408-469aaa80-999c-11e9-8e4e-87215ba8e463.jpg)

**Comment by TerryCavanagh** [comment]
Honestly, I think that might be a little demotivating. Gonna leave it as is!
