### ISSUE TITLE
Playing tutorial twice in one session causes fight background not to be loaded the second time

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#239]
![image](https://user-images.githubusercontent.com/11216597/60374418-5af99a00-99d2-11e9-9fab-f55dc4b8b9d1.png)
Repro: Do tutorial, die to hothead, reset progress from the menu, do tutorial again. No fight backgrounds will appear until you finish the tutorial. ("Floor 2", the first floor after you defeat Jester, will be completely normal.)

**Comment by TerryCavanagh** [comment]
Fixed.
