### ISSUE TITLE
Editor no longer works

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#249]
Trying to add equipment/a card/a spell, trying to upgrade, or trying to level up all bring you back to the "proceed at your own peril!" screen and resets the character.

**Comment by ncrecc** [comment]
Huh, works for me. (Windows 10)

**Comment by TerryCavanagh** [comment]
Suspect this one is a reappearance of the older bug where playing a game, *then* using the editor in the same session can sometimes prevent the editor from working. I'll have another look!
