### ISSUE TITLE
Suggestion: misc character select screen improvements

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#250]
* a back to title button (you can use the one in the esc menu but having a visible one like in the editor might be nice)
* see "wins/losses" before you unlock episodes

**Comment by TerryCavanagh** [comment]
First one is done! Second one I don't think I want to do - shying away from showing losses, especially early in the game, and I don't think people care about win counts until they have episodes unlocked.
