### ISSUE TITLE
[Suggestion] add no equipment fallback for Reversal/Copycat

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#256]
Inventor's gadget skill creates two situations where entering a fight with no equipment guarantees victory:

**1. Against Copycat:** If you have a gadget that inflicts damage, removing all your items will deprive Copycat of any equipment but still allow you to win the fight by using the gadget.

**2. Reversal Gadget:** Reversal extends this issue to all fights where the gadget is at play, as it allows a player to switch an empty loadout for the enemy's weapons.

In the first case, perhaps Copycat should have a default (scary!) loadout if no equipment is returned by target.getcurrentequipment().

In the second, either the gadget shouldn't operate if you have no equipment of your own to reverse with the enemy, or it should provide the enemy with something else if getequipment(self) has returned no equipment.

**Comment by ncrecc** [comment]
Your suggested "Against Copycat" solution doesn't work if you just bring a card that can't deal damage (e.g. a passive like Scrap Kettle) and a damaging gadget.

**Comment by hunky-dory** [comment]
True — I think the same applies to the second situation too. It's a real can of worms!

**Comment by YinYin-Falcon** [comment]
An idea for reversal: only exchange cards of your own with cards of the opponent, one by one (no cards, no exchange).

An idea for copycat: reverse copy an original damage card from the damage gadget.

**Comment by TerryCavanagh** [comment]
Happy to live with the weirdness of this rather than trying to plaster over it at this point. I considered e.g. just excluding Copycat from Inventor, but technically I'd also have to exclude them from Witch and Robot too. Players who think of it seem to enjoy outplaying Copycat in this way, though, so I'm thinking it's probably a nice thing to just leave in there as is.
