### ISSUE TITLE
Thief stealing from Copycat returns a card from the previous enemy's pool on the first turn

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#260]
This is before Copycat has initialized its inventory. Probably fixable by forcing copycat to set up its inventory before battle starts.

**Comment by paceheart** [comment]
Reproduced in RC5.
![Dicey Dungeons Aug 10 02-27-44PM copycat copies from my previous fight](https://user-images.githubusercontent.com/38589027/62827001-1fc6bb00-bb7b-11e9-931a-fd72a182cd8f.png)

**Comment by TerryCavanagh** [comment]
Fairly certain this is fixed!
