### ISSUE TITLE
Character trapped on stairs

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#28]
![image](https://user-images.githubusercontent.com/2874150/57505582-40913180-733c-11e9-91c5-1026109709fc.png)

![image](https://user-images.githubusercontent.com/2874150/57505585-45ee7c00-733c-11e9-9927-67efb2c883ad.png)

**Comment by mrcdk** [comment]
Can we have some more information about this one? I think I've fixed it but I'm re-reading it and now I'm not so sure 😅 With `clicked on the shop, then on the exit` do they mean clicking on the shop and while the separation animation or fade is running clicking on the exit? if that's what they mean then that's fixed and people won't be able to click anywhere else until the animations are finished.

**Comment by TerryCavanagh** [comment]
It sounds like that was exactly the cause! Fixed.
