### ISSUE TITLE
Robot CPU variables are forgotten if you restore a save

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#282]
Specifically, the CPU target:

![image](https://user-images.githubusercontent.com/2874150/60398249-201c7100-9b4e-11e9-8e87-dd80f25684a7.png)

**Comment by paceheart** [comment]
I lost 4 CPU to this by saving and reloading at the beginning of Floor 5, and it was a fun challenge! e.g. respec to remove Mechanical Arm and focus on dealing more damage with fewer dice. I managed to beat Aoife with Target 11.
![Dicey Dungeons Aug 03 03-21-37PM Aoife Target 11](https://user-images.githubusercontent.com/38589027/62417400-fea61d80-b602-11e9-9d05-74830dedd18e.png)

What does the Skeleton rule do if you're Robot? It could do something like this - lower your CPU Target by 4. (or 3 if you nerf Skeleton rule for other classes)

**Comment by mrcdk** [comment]
Fixed
