### ISSUE TITLE
Probably scrap Last Laugh?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#292]
It's basically a sure-win. The only way to make it fair would be to put it on a properly huge countdown, and at that point I'm not sure it's interesting.

**Comment by onetruepurple** [comment]
Worth noting the original intention was to make it like Divine Rod (needs 4x6).

**Comment by TerryCavanagh** [comment]
Actually, this is fine? It takes three turns to kick in, which you still have to survive for, so it's only really useful against bosses. Also, I feel like I barely see it streams, so clearly it's not as OP as I think it is. This is fine as is.
