### ISSUE TITLE
Allow refund if you decide to not upgrade an item in the shop.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#295]
The current behavior is if you realize you do not want to upgrade an item and decide to leave the shop, the shop keeps the money. Their should either by a cancel button or ideally automatically refund the gold amount when "leave" is selected.

**Comment by ncrecc** [comment]
Or present the interface such that you only pay once you upgrade a specific item, rather than paying just to get the chance to upgrade something

**Comment by ncrecc** [comment]
Same with copying equipment by purchasing a blueprint

**Comment by TerryCavanagh** [comment]
Done!
