### ISSUE TITLE
Copycat is immune to burning? dice.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#296]
Playing at PU Inventor and having Copycat be immune to burn?  can make it really a challenge when you have a burn build going with a burn gadget equipped and he has no negative effects but can inflict them.

Codyfun123 explained about how Copycat gets a copy of equipment each turn so I understand why it happens it just feels a little off.

**Comment by TerryCavanagh** [comment]
Huh, that’s weird - I have no idea why copycat would be immune to burn?. Is this maybe the burn not working on countdown equipment bug?

**Comment by ncrecc** [comment]
Copycat resets his layout every turn to what was in your inventory on turn 1, I think.

**Comment by TerryCavanagh** [comment]
Fixed!
