### ISSUE TITLE
Focus and Dice Manipulation Gadgets only work on unplaced dice. Description says all dice.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#298]
This one is probably a little trivial.

Focus text is : "All dice become 6" which apparently isn't _quite_ true.

I was playing as Inventor PU and had Calculator. I had a 1 and placed that in Calculator.

Then I hit focus and I got all 6's except for the placed dice in Calculator.

I had no idea that behavior existed. Maybe I'm slow?

Edit: I should go ahead and expand this to "any placed dice are not affected by Focus or Gadgets that manipulate dice". For example, Megaflip only flips unplaced dice.

**Comment by TerryCavanagh** [comment]
True, but I don't think it's worth complicating these descriptions with this edge case explanation at this point.
