### ISSUE TITLE
Sad Verse and Sonic Wave are identical except size and Sad Verse's lack of PU counterpart

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#299]
Ice Shard and Snowball at least have differing upgrades. Ice Shard and Ice Crystal are also identical (and Ice Crystal lacks a PU counterpart), but Ice Crystal is bestowed by Crystallize, which should be enough of a difference.

**Comment by TerryCavanagh** [comment]
I'm ok with this.
