### ISSUE TITLE
Description for Copper Shield+ is confusing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#3]
![](https://i.frogbox.es/lo8)
Add 2 shield? What's the die for, then? Doesn't sound much like an upgrade from adding 2x shield.

**Comment by TerryCavanagh** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/2874150/57507449-32461400-7342-11e9-9bba-00e0499353aa.png)
