### ISSUE TITLE
Enemy countdown cards set off by Wrecking Ball don't actually activate

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#300]
![image](https://user-images.githubusercontent.com/11216597/60455727-3d604680-9c05-11e9-9d01-2ce2f65456ad.png)
Copycat used Wrecking Ball to get Plaster to 0, but Plaster didn't actually activate. It stayed at 0 until the next turn, where it was back at 2.

**Comment by TerryCavanagh** [comment]
Fixed!
