### ISSUE TITLE
Consider a Rose redesign?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#302]
Strongly argued for by Jackeea:

![image](https://user-images.githubusercontent.com/2874150/60539756-5e0fc580-9d05-11e9-9807-ec22412fe013.png)

![image](https://user-images.githubusercontent.com/2874150/60539762-649e3d00-9d05-11e9-821f-800dd5b345d6.png)

![image](https://user-images.githubusercontent.com/2874150/60539785-7089ff00-9d05-11e9-8268-85b79243fa60.png)

![image](https://user-images.githubusercontent.com/2874150/60539793-754eb300-9d05-11e9-8484-87c01b180e22.png)

**Comment by ncrecc** [comment]
Rosewood Sword may as well do x damage, or x+2 damage, or something. Guaranteed 6 damage feels bad

**Comment by TerryCavanagh** [comment]
This was great, but Rose works pretty well now as a rare level 1 enemy and I've got no plans to change that anymore.
