### ISSUE TITLE
Suggestion: force player character map animation to sync with enemy animations

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#306]
Because this looks a little odd:
![](https://user-images.githubusercontent.com/11216597/60614892-daed7e80-9d9b-11e9-8eef-b82778391ffe.gif)

**Comment by ncrecc** [comment]
This was added in rc1

**Comment by ncrecc** [comment]
Back in RC2. Maybe I lied.
![lide](https://user-images.githubusercontent.com/11216597/62398194-02279f00-b546-11e9-9220-ae7821007a14.gif)
(Warrior's bobbing is because the gif dont loop right)

**Comment by TerryCavanagh** [comment]
Nah, happy to leave this be.
