### ISSUE TITLE
| (newline) in gadget description isn't interpreted as newline

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#307]
![Screenshot 2019-07-04 at 09 19 22](https://user-images.githubusercontent.com/48322734/60651092-5fdca480-9e3d-11e9-9330-cafce22fd6bf.png)

**Comment by TerryCavanagh** [comment]
No longer planning to support newlines in gadget descriptions, and this particular gadget has been fixed.
