### ISSUE TITLE
Enemies should be able to advance Lock? by placing a die in a multi-slot card, but they never do

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#310]
This is something the player can do but the AI never considers. If this were implemented for AI, it would make enemies like Skeleton and Aoife harder to break. However, this might make decision-making more complicated with the notion that AI would want to take dice out of multi-slot cards if they're too low and were only inserted to further Lock?.

**Comment by TerryCavanagh** [comment]
Yep, need to fix this - but there's a duplicate on the main repo, so closing this one.
