### ISSUE TITLE
PU Inventor vs. early game damage

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#317]
Every PU Inventor run left me feeling like the early game does not have enough damage dealing items. So I put the generators to a comparison:

|Chest items available normally|Chest items available in PU|
|---|---|
|Sword **(6)**|Spannersword **(1)**|
|Staff **(6)**|Gemstone Staff **(6)**|
|Crossbow **(9)**|Wrecking Ball **(4)**|
|~~Spark/Snowflake/Buzzer/Whisper~~|~~Knitting Needle~~/Mosquito Bite **(1)**|
|~~Leather Armor~~|~~Hi Vis Jacket~~|
|~~Bump~~|~~Saw Wave~~|
|~~Healing Crystal~~|Elastic Heart **(3)**|
|~~Lockpick~~|~~Berlin Key~~|
|Spike **(2)**|Double Edge **(12)**|
|Keyblade **(3)**|Blast Chiller **(4)**|
|*no equivalent*|Tetraphobia **(4)**|
|**Store items available normally**|**Store items available in PU**|
|Dagger **(3/6/9**)|Nunchucks **(6/12/18)**|
|Boomerang **(12)**|Big Stick **(6)**|
|Crystal Sword **(15)**|Rubber Mallet **(6)**|
|Venus Fly Trap **(6)**|~~Change Machine~~|
|Keyblade **(3)**|Screwdriver **(6)**|
|Six Shooter **(lots)**|Sledgehammer **(8)**|
|*no equivalent*|~~Antispatula~~|
|*no equivalent*|Gold Dagger **(1)**|
|*no equivalent*|Silver Dagger **(1)**|

This analysis reveals:

- PU Inventor actually has *more* damage dealers available in chests than regular Inventor...
- ...however, they're mostly not as good: Gemstone Staff is fine, Mosquito Bite is tiny but even 1 damage helps on floors 1 and 2, and it makes a good gadget too), Wrecking Ball is OK but you won't always find countdown items to synergize with it, *but* Spannersword is immediate gadget fodder, Blast Chiller is expensive, Elastic Heart is limited at MAX3 and Double Edge is just a bad item I never use
- PU Inventor has a bigger variation of damage dealers and dice manipulators in the store, whereas regular Inventor has only the former
- PU Inventor's store bought damage dealers are *weak* compared to the ones regular Inventor gets: the strongest one here is Sledgehammer (appears in 30% of all runs) and Nunchucks (difficult to use without a Lockpick equivalent)

I'd think of suggestions, but I'm out of time typing this :)

**Comment by onetruepurple** [comment]
Don't think this one will be adressed at this point. :'(

**Comment by TerryCavanagh** [comment]
Yep, probably not at this point, but this was a really great analysis 😄 

(The episode basically seems to work as is, so probably not gonna mess with it now)
