### ISSUE TITLE
Reduce by? seems to block some wrong status effects

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#320]
In Parallel Universe quests, I have seen Reduce by? blocking positive status like "Requip" or not blocking some negative status like poison, fire or freeze (Inventor side quest)

**Comment by onetruepurple** [comment]
Reduce? will only block as many "countable" effects as it itself has. So 2x Freeze? vs. 1 Reduce? will still yield 1 Freeze?.

**Comment by TerryCavanagh** [comment]
Oh, yep - this is correct behaviour. Should possibly make it clearer, though.

**Comment by ncrecc** [comment]
This gets annoying with Hi-Vis Jacket and gadgets granting status effects (like re-equip), maybe - this would be kind of hacky - it should only apply to status effects the enemy inflicts upon you. Or make a distinction between "good" status effects that shouldn't be blocked and "bad" status effects that should, but that might be hackier.

**Comment by ncrecc** [comment]
Fixed in 1.9 with the introduction of the "Blocked by Reduce?" column in statuseffects.csv
