### ISSUE TITLE
 Particle Accelerator damage indicator doesn't increment.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#322]
Leads to some confusion as to what the item does. Nothing visibly happens when you throw dice in there. Just a 1 damage.

Jackeaa also mentioned Kapow and others with this in their description as also having the same issue:

![unknown](https://user-images.githubusercontent.com/40739964/61004752-b281f900-a334-11e9-8dbd-5864ef52cd90.png)

https://drive.google.com/file/d/1FkaqOW66ldzwpYCT8QThbzX5l5M8YmWS/view

**Comment by TerryCavanagh** [comment]
Fixed.
