### ISSUE TITLE
Reversal and Encyclopedia can create too many gadgets.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#323]
I used Encyclopedia and got Reversal. 
Swapped equipment and finished out the turn.
Used Reversal again (after using Dodge) and received a reactivated Encyclopedia, which I used and now have 3 gadgets. I guess because Loud Bird's Encyclopedia hadn't been activated yet. 

 Not sure if this would be better to nerf or to allow and accommodate for ? I was pleasantly surprised.

Edit: And also Encyclopedia can be copied producing the same issue.

![rev](https://user-images.githubusercontent.com/40739964/61135727-3d2b3b00-a490-11e9-8b6f-513d1ad05e7c.jpg)

![rev](https://user-images.githubusercontent.com/40739964/61137813-37375900-a494-11e9-945b-ed959e41da3f.jpg)

**Comment by TerryCavanagh** [comment]
I'm planning to change reversal to be a (once) gadget, which will prevent this.
