### ISSUE TITLE
Aoife's art does not match with her equipment

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#326]
Of course, not every enemy is a 1:1 translation, but Aoife handling a sword and a tiny shield is a particularly big mismatch.

(Too late to fix?)

**Comment by TerryCavanagh** [comment]
Yeah, I don't really know what to do about this at this point in development. :(

The best option would seem to be to ask Marlowe to create a brand new enemy design that's a better fit for the actual design, and then create a new monster with the old Aoife sprite. But it might be too late for that. It is one of those nagging things that keeps annoying me, though.

(Another solution would be to redesign Aoife so her moveset better matches her equipment, but I like that a lot less, I think.)

**Comment by onetruepurple** [comment]
I would say this is resolved in RC1, but I do kind of miss Shield Bash :'(
