### ISSUE TITLE
Consider making Hammer_deckupgrade shock on even, instead of always shock

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#327]
Would've made this part of #259 but I forgot

**Comment by ncrecc** [comment]
I copy-pasted the original title and forgot to change "weaken" to "shock", cool.

**Comment by ncrecc** [comment]
Maybe do the same sort of thing with Dust Cloud+

**Comment by TerryCavanagh** [comment]
Nah, it's an unnecessary complication at this point, especially with the localisations needing to be changed for this. I just don't think it's important enough for the amount of work that it would take.
