### ISSUE TITLE
Many weapons have their sfx missing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#33]
This applies to Snowball and Parrying Dagger, at least.

**Comment by ncrecc** [comment]
Shield Bash doesn't seem to have any sfx either for some reason.

**Comment by ncrecc** [comment]
Nor does Dark Shadow.

**Comment by TerryCavanagh** [comment]
Fixed (And added safety checks to reduce the chances of this happening in future!)
