### ISSUE TITLE
Silence? persists after Fleeing

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#330]
![image](https://user-images.githubusercontent.com/32357485/61564265-fa5bfb00-aa6d-11e9-86a7-bb25b5b70444.png)
Was Silenced against Loud Bird, but fled the fight. Now I'm starting a fight against Super Alchemist (who can't Silence) and my limit break's still weakened.

**Comment by TerryCavanagh** [comment]
Fixed.
