### ISSUE TITLE
Suggestion: If you have more cards than fit on the screen (e.g. by furying crystallize), bring in rightmost cards once a column is cleared, ala Jester's deck

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#331]
Super zany but might be a good solution. The skillcard should probably remain on-screen no matter what, also like Jester, which would fix PU Robot being unable to do anything by pushing Calculate off-screen after furying Precious Egg:
![robro](https://user-images.githubusercontent.com/11216597/61582184-5453d380-aaf5-11e9-94a1-dc53d6044e99.gif)
So if this were implemented, turn 2 of the above image would have calculate on the right instead of four-leaf clover, and then after any card is used, four leaf clover would slide in

Dunno what should happen after battle is over, I guess four-leaf clover would go to the inventory or be trashed if there's no inventory space available

**Comment by TerryCavanagh** [comment]
Not planning to do this (but I was, for a long time! Oh well.)
