### ISSUE TITLE
Script: After Level Up doesn't run after continuing a saved game

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#335]
If you have a custom variable that's set on game start and increased by levelling up, only the On Game Start script will run after loading a saved game, resulting in your custom variable being set as if you just started the game

**Comment by TerryCavanagh** [comment]
So much has changed since this issue that I'm not sure it's a good idea to fix this particular behaviour anymore... presumably modders are working around it now, and it would cause problems to repair it/potentially break some older mods? Unfortunately I think I missed the boat on this one :(
