### ISSUE TITLE
All equipment with free dice have bugged descriptions

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#339]
![broadswordbug](https://user-images.githubusercontent.com/19874772/61741818-9758b580-ad46-11e9-9afd-fb88e71fc2f2.gif)
It does the right amount of damage, but the description show the wrong number.

**Comment by mothbeanie** [comment]
seems like it's not just broadsword

**Comment by TerryCavanagh** [comment]
Fixed!
