### ISSUE TITLE
[rc1] Music may be too loud relative to SFX

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#340]
Particularly in the Jester battle (which was the first fight with background music for me), it was very hard to hear the sound effects over the music with default settings.

**Comment by sstangl** [comment]
Setting Music to around 70% feels better.

**Comment by sstangl** [comment]
It only feels too loud in headphones -- on a laptop speaker, I can't actually tell the difference between 70% and 100%.

**Comment by TerryCavanagh** [comment]
(Music is in the middle of being final mastered, but this issue refers to an older build, so I'm closing it to prevent confusion)
