### ISSUE TITLE
The Bestiary looks hella cool but the black textbook needs more opacity

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#342]
![image](https://user-images.githubusercontent.com/2095534/61742290-0f4ccd00-ad93-11e9-82a0-abe79985d571.png)

**Comment by sstangl** [comment]
At least on my screen, the slider can also blend into that light in the background.

**Comment by TerryCavanagh** [comment]
I can't remember if this got tweaked or not since this issue, but I've seen this screen a lot with localisation testing and I'm pretty happy with it as is right now.
