### ISSUE TITLE
The game HATES thorns and will crash if you apply them to yourself

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#35]
Cactus had three dice locked, unshocked its thorns card, used the card once successfully, used the card another time and triggered curse? (giving me one thorn), then used the card again and... the game hung for about 10 seconds, then closed without warning. I have no clue what caused this. Yikes!

**Comment by ncrecc** [comment]
![](https://i.frogbox.es/loh)
Luckily I got the exact same RNG when continuing and was able to capture a gif of what happens (I didn't know the game was seeded so precisely!)

Oh yeah, and fury bar is overwide but I think that's a bug regarding quitting/crashing and continuing, I didn't notice it the first time around.

**Comment by ncrecc** [comment]
[12:46 PM] onetruepurple: I gave myself 5 Thorns and then the game froze and shut down without any error on Cactus' turn

Maybe this is a bug regarding thorns on the player?

**Comment by ncrecc** [comment]
https://cdn.discordapp.com/attachments/552131784939405332/576818176445120522/Dicey_Dungeons_11.05.2019_19_08_59.mp4

**Comment by TerryCavanagh** [comment]
This is kind of a terrifying bug because I can't reproduce it with the debugger on :(

For v0.17, I'm just going to reduce it to a "lesser" bug by making the AI completely ignore thorns when estimating damage, which should fix it, but will mean at the AI might actually be dumb enough to kill themselves. Still, better than a crash, for now.

**Comment by TerryCavanagh** [comment]
Oh, hah - it's just an infinite loop. Not going to dig into it right now, but it should be an ok fix eventually.

![image](https://user-images.githubusercontent.com/2874150/58021366-dc474c80-7b49-11e9-84b5-9fa1d2a3b4f2.png)

**Comment by TerryCavanagh** [comment]
Actually, I just went ahead and fixed it now.
