### ISSUE TITLE
Enemy doesn't play optimally with re-equip next

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#361]
Cactus had six, four, one, and re-equip next (from Pirate). Optimally it should use six on cactus spear, put one in cactus shield, then put four in cactus spear for a total of 11 damage and 1 thorns. Instead, it put one in cactus shield (wasting re-equip next) and six in cactus spear for 7 damage.

**Comment by TerryCavanagh** [comment]
Fixed!
