### ISSUE TITLE
Blind dice being modified via Berlin Key aren't unblinded

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#365]
You know what value the die is going to be, but the game acts like you wouldn't

**Comment by TerryCavanagh** [comment]
Oh, cool! It should work exactly like this, I think.

**Comment by ncrecc** [comment]
Nope, this is back:
![germany](https://user-images.githubusercontent.com/11216597/63274794-6b115580-c26e-11e9-866f-73b366041536.gif)
