### ISSUE TITLE
OSX error message for Steam version exposes user folder name

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#369]
![Screenshot 2019-07-24 at 11 22 37](https://user-images.githubusercontent.com/48322734/61786515-c41fd200-ae05-11e9-98a3-407e2c42453c.png)
For screen-capturing bugs, it'd be nice if it didn't :)

**Comment by mrcdk** [comment]
I don't see the issue here, that information is for the user to be able to locate the crash log so they can report it. You don't need to screenshot that popup.

**Comment by hunky-dory** [comment]
For me at least, the issue is that if you are streaming the game and it crashes, it exposes your user folder name. Maybe you could reference the crash location as ~/Library/Application Support/Steam/steamapps/common/etc etc, which would convey the same information?

I imagine most people will get to the location by 'Browsing local files' from within Steam. If not they'll use finder's Go menu and hold Alt to make Library appear and browse from there. And if not that they'll use 'Go to Folder..' where `~/Library/etc` would get them to the folder.

**Comment by mrcdk** [comment]
Fixed.
