### ISSUE TITLE
Pickpocketing causes UI to overlap cards

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#370]
![Screenshot 2019-07-24 at 11 46 43](https://user-images.githubusercontent.com/48322734/61788096-20d0bc00-ae09-11e9-80d0-d821feb10e7e.png)

This issue was previously marked as fixed but seems to have returned:
https://github.com/TerryCavanagh/diceydungeons.com/issues/393

**Comment by TerryCavanagh** [comment]
Have decided to live with this - there's really just no room for it anywhere else and it's not a huge deal.
