### ISSUE TITLE
Jester can appear multiple times on a run if you reload your savefile

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#371]
![image](https://user-images.githubusercontent.com/2874150/61789822-8fb01400-ae0d-11e9-9364-5c12d4733ee1.png)

**Comment by TerryCavanagh** [comment]
Related issue:

![image](https://user-images.githubusercontent.com/2874150/61790382-ee29c200-ae0e-11e9-9860-ced0aab29f8d.png)

My guess is that the save files just aren't handling Jester related issues correctly, and that both of these will go away if I "save" the actual Jester state in the savefile.

**Comment by hunky-dory** [comment]
On Witch's first episode (where I take it you're supposed to meet, defeat and unlock Jester?) the problem also occurs, and Jester definitely hasn't appeared beforehand.

More bizarrely, in all these situations, it seems that double reloading will return it to the correct Jester state. I tested this a fair amount to make sure it wasn't random, and it does seem to be switching between Jester & non-Jester every reload:

```Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal
Floor.hx:397: Jester will appear on this run as the boss!

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal
Floor.hx:397: Jester will appear on this run as the boss!

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal
Floor.hx:397: Jester will appear on this run as the boss!

Game.hx:2837: Continue save loaded successfully
Game.hx:1419: witch_normal

etc
etc
```

**Comment by TerryCavanagh** [comment]
Fixed!
