### ISSUE TITLE
You can end up with no equipment by watching a cutscene and exiting the game

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#374]
1. Play an episode with triggering the second cutscene
2. Go through the cutscene until you start the game
3. Go to the title screen without looking at the inventory
4. Continue the game

Now you have no items except for the skillcard
![](https://cdn.discordapp.com/attachments/552131784939405332/603578949561352193/unknown.png)

**Comment by TerryCavanagh** [comment]
Possibly the same as https://github.com/TerryCavanagh/diceydungeonsbeta/issues/482

**Comment by mrcdk** [comment]
Fixed
