### ISSUE TITLE
Lock not stacking for robot

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#375]
![Screenshot 2019-07-24 at 16 20 39](https://user-images.githubusercontent.com/48322734/61806282-58525f00-ae2f-11e9-9d1e-e150fde93b06.png)
Paper Knight should have locked two dice but only the first dice ended up getting locked

**Comment by musicalentropy** [comment]
Got the same problem against the same enemy

**Comment by hunky-dory** [comment]
Same issue occurs in You Choose, You Lose:
![gif](https://giant.gfycat.com/OccasionalNarrowHarlequinbug.gif)

**Comment by TerryCavanagh** [comment]
Unbelievably, this one is still in the latest version of the game (v1.9 right now). Thankfully, there are many issues about it over on the main repo.
