### ISSUE TITLE
Weakened Ray Gun is unchanged from normal ray gun

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#378]
![Screenshot 2019-07-24 at 17 48 41](https://user-images.githubusercontent.com/48322734/61812487-8047bf80-ae3b-11e9-9205-a7b6a0fecc7c.png)
![Screenshot 2019-07-24 at 17 44 55](https://user-images.githubusercontent.com/48322734/61812493-8342b000-ae3b-11e9-820f-6c6bf2629692.png)

**Comment by ncrecc** [comment]
Still around

**Comment by TerryCavanagh** [comment]
Fixed!
