### ISSUE TITLE
Jinx/Slapsies mouseover description doesn't match the what is displayed on the HUD.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#381]
Maybe trivial. It just seems the mouseover description should update as opposed to it saying what the initial condition of the inflicted status was.   The HUD shows me getting slapsies in 1 turn (which is the important part) but it makes the mouseover verbiage a little confusing...like I'm going to get it again or something.

![jinx](https://user-images.githubusercontent.com/40739964/61815263-dc98e800-ae17-11e9-92ac-7e6ad6c3acb2.jpg)

**Comment by TerryCavanagh** [comment]
Fixed!
