### ISSUE TITLE
Cursed Item in Jester Deck Behavior.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#382]
As it is right now the when a Jester gets cursed his card disappears. Would it be better  for the next card to populate? Other classes when cursed have the behavior of having the cursed item disappear but doesn't penalize them further by limiting their equipment pool.  Jester is further penalized by being left with only 2 cards.

![cursed](https://user-images.githubusercontent.com/40739964/61817062-a65d6780-ae1b-11e9-8c60-bd06d164414a.jpg)

**Comment by hunky-dory** [comment]
Gif of this in action:
![gif](https://giant.gfycat.com/ElderlyBaggyCaribou.gif)

**Comment by TerryCavanagh** [comment]
Fixed!
