### ISSUE TITLE
Certain aspects of upgraded gray cards stay gray

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#387]
![image](https://user-images.githubusercontent.com/11216597/61839412-6918ca00-ae5b-11e9-87e9-379c0d1c5067.png)
![image](https://user-images.githubusercontent.com/11216597/61839447-8ea5d380-ae5b-11e9-9a77-defbee307b16.png)
Ribbon, countdown background, and filter should all have unique colors for white cards

**Comment by TerryCavanagh** [comment]
Fixed!
