### ISSUE TITLE
Stack the deck to soften these kind of unfun situations for Jester

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#389]
![image](https://user-images.githubusercontent.com/2874150/61866122-83d75700-aecc-11e9-84e5-11081fef454e.png)

I could have a simple check: if you have a hand with restrictive dice slots and happen to roll so that you can't do anything, then just secretly change the dice values so that you can. It'd barely be noticeable, and would prevent unfun situations like this.

**Comment by ncrecc** [comment]
Still might not work much with freeze and potentially freeze?. Randomizing the cards in your hand and upcoming cards at the start of each turn and secretly only granting usable cards might be a better choice, though randomizing would definitely take away some amount of strategy. This is tricky :/

**Comment by ncrecc** [comment]
I suggested nerfing freeze so it can set dice to 1 *or 2* (but still setting 2s to 1 no matter what) so at least using even cards is easier, but this might be a big change for so soon before release

**Comment by TerryCavanagh** [comment]
Not planning to do any deck stacking anymore, but I've basically fixed this by excluding certain enemies from Jester runs, which I'm satisfied with.
