### ISSUE TITLE
Music occasionally waits for a split second before looping

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#39]
Pretty minor bug (though it does sound slightly jarring) and I'm not sure what causes it. Not a bug with the audio files themselves, but with how the game handles them. Most noticeable when lingering around on the overworld.

**Comment by TerryCavanagh** [comment]
Does this one still happen? I don't think I've heard this one happen in a very long time.

**Comment by ncrecc** [comment]
I can't think of the last time it happened, either. Probably safe to assume plenty of audio handling's been changed since then
