### ISSUE TITLE
Backpack dragging: 1 size items are not always switched with 2 size items

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#392]
![gif](https://giant.gfycat.com/MajesticMammothGrackle.gif)
HD: https://gfycat.com/majesticmammothgrackle

Some one-size items cannot be drag-switched with two-size items. I'm at a loss to what might be causing this, but it appears to happen to some instances of items and not others.

If it affects an instance of an item, it can be reproduced for that instance of the item consistently.

**Comment by TerryCavanagh** [comment]
Fixed!
