### ISSUE TITLE
Keymaster didn't receive additional dice from a backfired Cursed?

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#396]
I used Lockpick to split a dice. The Cursed? backfired, and the two dice were stuck at the top of the screen. "Oh no," I thought, "now Keymaster has three dice, that's really bad!"

But when their turn came, Keymaster unexpectedly had only one dice.

**Comment by ncrecc** [comment]
They weren't stuck there, you should just be able to drag them into your own cards.

Dupe of #40 (I think)

**Comment by ncrecc** [comment]
Resolved in 1.9 beta, curse?d dice-giving equipment now inflicts illuminate on the opponent
