### ISSUE TITLE
Precious Egg and similar should be immune to fury/have unique behavior

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#398]
When furied, precious egg duplicates, and this can make your skillcard inaccessible which is potentially run-breaking. Remix robot getting fury is really common so this can be a problem! Maybe it should just do nothing when used with fury, or skip a step? (Ex. precious egg 6 skips to 4, precious egg 2 just gives you the item inside)

**Comment by ncrecc** [comment]
What happens if you fury precious egg 1? Does it insert a 1 into the card you receive? What if the card doesn't take 1s?

**Comment by ncrecc** [comment]
Fixed, e.preventdefault and e.maintainfury are set to true for items like Precious Egg when they're furied now, although re-equip remains an issue

**Comment by TerryCavanagh** [comment]
Fixed.
