### ISSUE TITLE
If a 6 gets frozen (as Robot only?) in Remix while you have Hothead active, the 1 catches fire

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#402]
Probably a more general bug. There's also a bizarre bug I occasionally have where putting a 1 in Slingshot with the Hothead modifier randomly causes the resulting die to catch fire, but not sure how to replicate that or where it's coming from. (Was not using Bounty Hunter.)

**Comment by TerryCavanagh** [comment]
Fixed!
