### ISSUE TITLE
Redundant button on upgrade screen

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#404]
![image](https://user-images.githubusercontent.com/2095534/61968985-b02cc980-afd9-11e9-9f5f-ba0cc4d8a927.png)

**Comment by TerryCavanagh** [comment]
This is a good button: it helps with the "you're finished" flow of the screen, which would feel weird if it wasn't there and you had to hit the "exit" button. This arrangement could be a little cleaner, maybe, but it works fine as is.
