### ISSUE TITLE
Trading post sometimes gives item without taking requested item

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#405]
![gif](https://giant.gfycat.com/VelvetyDopeyBarnacle.gif)
HD: https://gfycat.com/velvetydopeybarnacle
Maybe when a one-size is traded for a two size?

**Comment by ncrecc** [comment]
Dupe of dd.com #569

**Comment by hunky-dory** [comment]
Closing as per above as dupe of:
https://github.com/TerryCavanagh/diceydungeons.com/issues/569
