### ISSUE TITLE
Overlapping dice do not respond to clicking as expected

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#407]
![gif](https://giant.gfycat.com/SecondhandDelectableHousefly.gif)
HD: https://gfycat.com/secondhanddelectablehousefly

When dice overlap --
Expected: clicking grabs the topmost dice
Current: clicking grabs the dice on the lowest layer underneath

**Comment by TerryCavanagh** [comment]
Duplicated in the main repo!
