### ISSUE TITLE
Slime Remix adds poison every turn instead of removing it

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#408]
Slime remix appears not to be acting as described
![Screenshot 2019-07-26 at 20 31 26](https://user-images.githubusercontent.com/48322734/61976833-b4121900-afe4-11e9-8310-08e305d3c3dc.png)

One more poison gets added each turn:
![gif](https://giant.gfycat.com/BelatedQuickFawn.gif)
HD: https://gfycat.com/belatedquickfawn

**Comment by ncrecc** [comment]
Not only does slime add poison, but it causes you to take one more point of poison damage than you would normally. None of this applies to the enemy.

**Comment by TerryCavanagh** [comment]
Fixed!
