### ISSUE TITLE
dice can get lost on arrow buttons

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeonsbeta#41]
![dice](https://user-images.githubusercontent.com/3826749/57567743-2019b380-73de-11e9-988e-09a44c606b36.gif)

**Comment by ncrecc** [comment]
Still around, mostly a problem with flee

**Comment by TerryCavanagh** [comment]
(duplicated on the main issues board, closing this as duplicate https://github.com/TerryCavanagh/diceydungeons.com/issues/1166)
