### ISSUE TITLE
Floor 4 trade in Thief's Remix occasionally doesn't give you any items

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#414]
![image](https://user-images.githubusercontent.com/32357485/61994937-bffbea80-b079-11e9-8a0c-09338e135ee1.png)
This is the logic (from `thief_remixgenerator.hx`) - it uses similar logic to the PU trade. However, there's no guarantee that the player will have one of Master Key/Nunchucks/Lockpick/Dagger - my starting equipment was Wrecking Ball + Pea Shooter, and my level up reward was Poison needle.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
