### ISSUE TITLE
Confuse potentially breaks item layout when player has used once-per-battle item on prior turn

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#415]
![Screenshot 2019-07-27 at 18 21 12](https://user-images.githubusercontent.com/48322734/61997614-d9159300-b09b-11e9-9704-c0c39358f001.png)

Seems to be repeatable (though it's on a reloaded save and I am having to exit to title and reload to repeat)

![gif](https://giant.gfycat.com/UniqueComposedKiskadee.gif)
HD: https://gfycat.com/uniquecomposedkiskadee

**Comment by TerryCavanagh** [comment]
Fixed!
