### ISSUE TITLE
Hard Handyman still has no idea what he's doing

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#418]
https://streamable.com/wcv9d

**Comment by onetruepurple** [comment]
![image](https://user-images.githubusercontent.com/2095534/61998566-4c2a0400-b0b2-11e9-8ded-5c8c01b2cea9.png)

**Comment by onetruepurple** [comment]
Same bug present more clearly here (0:34) https://streamable.com/c5vyu

**Comment by TerryCavanagh** [comment]
Not 100% sure if this is fixed or not, but I definitely remember seeing this issue over on the main repo, so this can be closed either way.
