### ISSUE TITLE
Capacitor+Pea Shooter remix load out for Robot is nonsensical

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#421]
1. Between two items with the same damage and the same countdowns, there is no reason to pick Pea Shooter over Capacitor unless it's shocked/weakened.

2. Barring lucky Jackpots, max 9 CPU makes it impossible to get more than 2 damage per round.

**Comment by TerryCavanagh** [comment]
Yep, agreed. Fixed!
