### ISSUE TITLE
Paper Knight remix applies extra dice to player and deducts dice from enemy each turn

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#422]
![Screenshot 2019-07-27 at 19 19 42](https://user-images.githubusercontent.com/48322734/61998154-87710680-b0a3-11e9-81e6-2e87af445055.png)

![Screenshot 2019-07-27 at 19 19 12](https://user-images.githubusercontent.com/48322734/61998150-70321900-b0a3-11e9-83f3-a7d6b8e77338.png)

**Comment by hunky-dory** [comment]
Adding a trace to the script, it seems that when the second rule is applied, self is now the enemy:
```
RemixTemplate.hx:29: Applying rule change: Rules.addextrascript("self.extradice = 2; trace(\"first script: \"+self.name); ", "startcombat"); Rules.addextrascript("self.extradice--; trace(\"second script: \"+self.name); if(self.dice + self.extradice < 1) self.extradice = 1- self.dice;", "beforestartturn");
hscript:0: first script: Warrior
hscript:0: second script: Hothead
```

**Comment by TerryCavanagh** [comment]
Fixed (before start turn scripts were broken, fixed them!)
