### ISSUE TITLE
Music during the final battle keeps skipping

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#425]
https://streamable.com/xjunp

**Comment by TerryCavanagh** [comment]
THANK YOU! I had no idea what was happening here, and this makes it 100% clear.

**Comment by ncrecc** [comment]
(This explains why I thought LL fight was going to freeze my computer - it tends to mess with audio a lot shortly before doing so)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/62276788-b63d0300-b43c-11e9-95a2-735f47f58296.png)

Yay, I got it to replicate

**Comment by onetruepurple** [comment]
Still valid in RC4

**Comment by TerryCavanagh** [comment]
This one's fixed now.
