### ISSUE TITLE
Damage modifier doesn't increment with the Rose remix

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#428]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/26709843/61999396-7d69fa80-b0d9-11e9-80f7-1ef19ef08927.gif)

**Comment by ncrecc** [comment]
To my understanding, it's not supposed to increment.

**Comment by TheMysticSword** [comment]
Ohh, that makes sense. I misunderstood it as "do more damage as you do more attacks"
