### ISSUE TITLE
Hothead Remix can burn non-six dice

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#429]
![image](https://user-images.githubusercontent.com/26709843/62000155-c1fd9200-b0e9-11e9-99aa-562fac2e5e15.png)
I had no Burn status, rerolled a dice with the Lucky Roll and got the burning five.

**Comment by TheMysticSword** [comment]
I also just got a burning 4 by rerolling with the Combat Roll.

**Comment by paceheart** [comment]
I got a burning 3 by putting a Blind 4 into spatulasword

**Comment by lcenine** [comment]
Had a burning 6 that I put into subdivide. It returned a regular 3 and a burning 3.

**Comment by TerryCavanagh** [comment]
Fixed!
