### ISSUE TITLE
Make Confuse more confusing, perhaps?

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#430]
Right now it's basically nothing more than a minor interface change if all your cards have unique requirements. What would spice this up is if, say, the numbers on countdown cards were obscured, "filter" slots (max 5, min 4, range, even/odd, needs x) were reduced to just a striped background, and the visual indicators for needs doubles/must equal x were taken away. Hint text particles like "needs 1, 3, or 5!" would be replaced with a generic "dice doesn't fit!", and something would also probably pop up if you insert the wrong dice into a needs double/must equal x card.

**Comment by TerryCavanagh** [comment]
Haha - it's a fun suggestion, but I think it's ok if sometimes it isn't especially confusing. In fact, I think pushing things too far might make it less fun - although, I do like the blind countdown number suggestion - might do that!
