### ISSUE TITLE
Lady Luck speaks out of turn

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#435]
![lady luck speaks out of turn](https://user-images.githubusercontent.com/38589027/62009006-a0fb6800-b10e-11e9-814a-44c5bf8a3c86.jpg)

Lady Luck laid down commandments a couple of turns ago, then I went into Options (to try to fix #56) and when I exited the Options screen, her "rules" dialogue repeated.

**Comment by TerryCavanagh** [comment]
Fixed!
