### ISSUE TITLE
Errors about undefined symbols appearing in the console

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#438]
![image](https://user-images.githubusercontent.com/32357485/62010891-aeddd700-b168-11e9-8b5f-56ca0aeaaf25.png)

These warnings happened after using Northern Lights (get 2 []s next turn) as Thief, after getting Val as a remix rule. Everything displayed correctly and the game didn't crash, though.

**Comment by TerryCavanagh** [comment]
These are fixed now, I think - it's essentially a warning about missing VFX badly explained in the error message
