### ISSUE TITLE
Suggestion: disallow player from touching burnt dice that would kill them

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#439]
I imagine this could be a frustrating scenario if you have the Dragon modifier and think "ok, I'm below 5 hp but if I just use this burnt dice I'll win... oops, that dice killed me"

**Comment by TerryCavanagh** [comment]
Nope, gotta let people grab those dice if they want to! I think it would destroy the drama of a fight you know you're going to lose if you realise you have no options, resign yourself to grabbing the last burning dice, and the game just... doesn't let you.
