### ISSUE TITLE
Multi-line dialogue text results in some of the text not displaying

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#44]
eg 1:
![image](https://user-images.githubusercontent.com/48322734/57569525-1d26bf00-73ee-11e9-8543-1f32b3af5388.png)

eg2:
![image](https://user-images.githubusercontent.com/48322734/57569528-26b02700-73ee-11e9-84e9-fb0f7aa00b4e.png)

**Comment by ncrecc** [comment]
Fixed a while ago

**Comment by TerryCavanagh** [comment]
This was a rendertexture thing! Fixed in v1.2 😄
