### ISSUE TITLE
Val's remix removed items from my inventory permanently

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#440]
My equipment was 2x Wrecking Ball, and some other items. On one of my turns, an item got swapped out for another Wrecking Ball. On the next turn, all Wrecking Balls were gone from my inventory, permanently.

**Comment by TerryCavanagh** [comment]
Looks like there are still some issues with the Val rule in v1.9, but they're different issues now, so this can be closed!
