### ISSUE TITLE
Bonus Round - Inventor and Jester ideas

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#447]
Inventor: In bonus round, Inventor always has the PU gadget screen. For more randomness/fun, perhaps it could only be the PU gadget screen if you choose the hard mode option, or when you start you'll randomly have the normal screen or the PU one.

Jester: In bonus round, Jester doesn't get to choose his starting gear and just gets his PU deck. He should probably be able to choose between the PU deck or the normal deck, or perhaps some mixed combination of the two?

**Comment by mothbeanie** [comment]
more for bonus round jester:
Call for Backup Warrior could be: [count]dmg +1 per bop/kapow
Call for Backup Warrior? could be: Add 3 to kapow/bop damage

so no matter what you get, it's still usable, even if the effect is different

**Comment by TerryCavanagh** [comment]
Good suggestions here, but not planning to change much here at this point.
