### ISSUE TITLE
Burning dice do not get frozen

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#448]
I Frozen 3'd a baby squid. It rolled 6 1. The 6 caught fire because Hothead, but it didn't get frozen - it stayed a 6. I think it should have turned into a 1.

**Comment by paceheart** [comment]
This happened again against Keymaster, but it was more interesting. He rolled a burning 6, put in in Lock 6, and put it in the resulting Keyblade. When it was returned, it finally got Frozen? and reduced to a 5. I imagine that if Warlock wasn't activated and it was regular-Frozen, it would have turned into a 1.

**Comment by onetruepurple** [comment]
Burning dice do not get frozen.

**Comment by onetruepurple** [comment]
Burning dice do not get frozen.

**Comment by onetruepurple** [comment]
Burning dice do not get frozen.
