### ISSUE TITLE
When Power Surge triggers Curse, you don't get your next card

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#450]
Jester Bonus Round. I had Curse 1 and used Power Surge. The curse triggered, and my third card slot remains empty.
![Dicey Dungeons can I get my next card pls](https://user-images.githubusercontent.com/38589027/62098055-7adce180-b24e-11e9-9b0a-ac78470035d9.png)

**Comment by paceheart** [comment]
Also why is it called "Robot?" instead of Robot, this isn't PU

**Comment by paceheart** [comment]
I put the 6 into the void and something ate it. Nothing appeared to happen.

**Comment by TerryCavanagh** [comment]
Fixed!
