### ISSUE TITLE
Jester's fight against the Vampire is buggy

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#454]
The last thing I did was using the limit break, then activated snap on two wooden stakes, one of them being still blocked by the lightning status. Then I clicked on next turn, and the Vampire had his dices, but the game was blocked because its equipment has never showed up, and I had to quit the game.

**Comment by TerryCavanagh** [comment]
Jester doesn't encounter Drake anymore, and probably not planning to change that at this point!
