### ISSUE TITLE
stray fire sprite hanging out on the Enemy Moves

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#455]
![Dicey Dungeons Jul 30 10-04-20PM fireman with a stray fire](https://user-images.githubusercontent.com/38589027/62180571-1d13cc80-b316-11e9-9086-5fade038f117.png)

Thief Bonus Round. I put a Burn?ing 6 in the stolen Fireball, then went to Enemy Moves and saw this stray fire sprite.

**Comment by mrcdk** [comment]
Fixed
