### ISSUE TITLE
Remix: Baby Squid can sometimes blind two dice

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#458]
![Screenshot 2019-07-31 at 19 51 49](https://user-images.githubusercontent.com/48322734/62239486-dcc35580-b3cc-11e9-9e0f-410a9a232312.png)
I wondered if it might be connected to Sticky Hands' go first innate?

**Comment by TerryCavanagh** [comment]
Yep, that's exactly what causes this! (and still causes it in v1.9, uff). There's a duplicate on the main repo, though.
