### ISSUE TITLE
Downgraded Bronze Cauldron's description just says "(reuseable)"

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#459]
![Screenshot 2019-07-31 at 21 10 03](https://user-images.githubusercontent.com/48322734/62244574-9de6cd00-b3d7-11e9-82e4-b9b625520726.png)
Will update with a screenshot if it happens again, but I think it's because the equipment.csv description is incomplete

**Comment by TerryCavanagh** [comment]
How is this still a thing, lol

(duplicated on the main repo)
