### ISSUE TITLE
Tutorial seems to have broken — clicking on map screen doesn't do anything

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#46]
Footage of issue:
![image](https://giant.gfycat.com/NippyPrestigiousIndianglassfish.gif)
https://gfycat.com/NippyPrestigiousIndianglassfish

To repeat:
1. delete/rename **dicey_progress.json**
2. Load Dicey Dungeons and select Warrior's first episode

**Comment by TerryCavanagh** [comment]
Fixed! Thank you! :)
