### ISSUE TITLE
[remix] Cowboy remix says "enemies will always roll a 6", but gives the player all sixes on first turn

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#460]
![Screenshot 2019-07-31 at 21 58 42](https://user-images.githubusercontent.com/48322734/62247796-8101c800-b3de-11e9-9dda-9c3f4590560e.png)
![Screenshot 2019-07-31 at 21 58 59](https://user-images.githubusercontent.com/48322734/62247807-852de580-b3de-11e9-84af-24cd76ef8611.png)
Each fight after the modifier began with me rolling three sixes

**Comment by TerryCavanagh** [comment]
Fixed!
