### ISSUE TITLE
Bonus Round gives you the same rule twice, crashes

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#461]
![Screenshot 2019-07-31 20 54 11](https://user-images.githubusercontent.com/38589027/62259889-81499580-b3d5-11e9-8fff-dc305354f1d0.png)
![dicey vacuum vacuum error](https://user-images.githubusercontent.com/38589027/62259911-9faf9100-b3d5-11e9-83e5-cbaa4b660e2f.PNG)

Also, is that the right pathname? steamapps/common didn't seem to have a diceydungeons folder, my saves seem to be In Appdata/Roaming/Terry Cavanagh Games/diceydungeons
and I don't see a crash log there

**Comment by TerryCavanagh** [comment]
Fixed!
