### ISSUE TITLE
Make Loud Bird a little rarer in Remix.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#464]
I have gotten Loud Bird more often than any other hard remix rule.

Out of the hardlist I have almost always have gotten Loud Bird, Skeleton or Sorceress. I have never gotten Bully or Bounty Hunter.

While Skeleton and Sorceress add some "fun" hard difficulty, Loud Bird can make it really grindy...especially if you have gotten him many times.

Currently I'm picking ones I have not gotten if they are offered, or  choosing a random one trying to get something new.

**Comment by TerryCavanagh** [comment]
Yep, this is rarer now.
