### ISSUE TITLE
Feature Request:  Allow a repick of the random rule change for gold or hp.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#465]
Some rule sets combos can make it very difficult to win. Other can be beneficial (like Snowman if playing Thief).

Instead of adding multiple Remix.preventclash  entries to try and eliminate every very difficult  ruleset combo, allow the player to have one opportunity to re-pick a randomly chosen ruleset for gold or hp, or perhaps give them one re-pick per game.

**Comment by TerryCavanagh** [comment]
Ah, good suggestion, but, not planning to do this at this point. (I think a shop item or Val allowing you a trade would have been the way to do this, probably)
