### ISSUE TITLE
some tutorial text boxes appearing simultaneously feels a bit overwhelming

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeonsbeta#467]
these two appeared at the same time for me
![image](https://user-images.githubusercontent.com/3826749/62321327-a6f0a080-b4a2-11e9-9dd9-574a84ce27c1.png)
![image](https://user-images.githubusercontent.com/3826749/62321468-fe8f0c00-b4a2-11e9-94ea-22d8b04ef6d2.png)

**Comment by TerryCavanagh** [comment]
Hmmm, I'm ok with this. (though I see your point)
