### ISSUE TITLE
odd visual glitch in the tutorial

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#468]
i think i had this in the last RC but i forgot to report it: after finishing the tutorial, the "line" part of the overworld map is briefly visible on the black screen for the next floor.
![weird graphical glitch](https://user-images.githubusercontent.com/19874772/62321515-b1d21380-b457-11e9-8a7d-41d00d0dd5bb.gif)
(sorry for low quality gif)

**Comment by lcenine** [comment]
Also had this happen.

**Comment by mrcdk** [comment]
Fixed

**Comment by TerryCavanagh** [comment]
So glad that this one is finally fixed 🎉
