### ISSUE TITLE
misc SFX feedback

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#469]
* not a fan of the new "walk" sfx. the echo effect it has is really strange sounding, and if you click multiple tiles in succession the weirdness is amplified. i feel like itd be better if it was just one or two taps instead of an "echo" noise. alternatively, you could put it, like, a second after the "descent" sound effect (maybe going in reverse, quiet to loud) so it sounds like the player is "walking in"
* warrior's and thief's voices are a bit too quiet, and either witch's is too loud or the volume the rest should be.
* the victory music is too loud!
* i feel like discarding and snapping cards as jester should have a sound effect! (maybe a whoosh for discard, and super satisfying finger snap for snapping?)

**Comment by mothbeanie** [comment]
* the rule screen in bonus round could have sfx! perhaps, like, the spinning carnival/arcade wheel sfx could play when you hit randomize and slows down until its chosen? and when a rule "slots in", there could be a "cha-gunk" sound like when a vending machine dispenses something

**Comment by TerryCavanagh** [comment]
Basically all this audio stuff got dramatically changed just before launch (like, days before launch)
