### ISSUE TITLE
If you're Cursed in the Lady Luck fight, selecting a new party member can trigger curse

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#479]
![selecting stereohead triggered curse](https://user-images.githubusercontent.com/38589027/62347291-d1e8ed80-b4be-11e9-8d42-570ac0ba3aac.png)

I imagine this could be especially bad if it happened with your last party member.

**Comment by paceheart** [comment]
Whoa, it happened to 4 of my attempted selects in a row! Exciting!

**Comment by TerryCavanagh** [comment]
I think this is fixed now, but if you or anyone else sees it before launch, let me know :)
