### ISSUE TITLE
Bear Smash limit break reverts to Unlucky Roll after first use

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#48]
![Screenshot 2019-05-11 at 17 38 08](https://user-images.githubusercontent.com/48322734/57572560-fda28d00-7413-11e9-940e-e4d5e207c03a.png)

 Not sure if this is specific to Thief, or if Joker/Inventor bear will revert to their class limit breaks as well

**Comment by YinYin-Falcon** [comment]
It never swapped for me at all (unlucky thief bear as well). Might be related to whether it's currently active/activating.
The limit break getting cursed permanently for the rest of the run is probably related too.

**Comment by hunky-dory** [comment]
I just tried it out with Inventor (by changing the generator to give me a Bear Potion instead of a Sword on the first floor). Here's what seems to happen:
1. If you use Bear Smash, it immediately reverts to the class limit break
2. If you charge the meter but don't use Bear Smash, you can see it change to the class limit break when the battle is won, as the HUD moves off screen
3. By your second Bear fight, it will always have reverted to the class limit break

**Comment by TerryCavanagh** [comment]
Fixed! Thanks for the notes on this!
