### ISSUE TITLE
Upgraded Battle Axes in Warrior's second episode are the same than not upgraded

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#481]

**Comment by TerryCavanagh** [comment]
Are you sure? Upgrading Battle Axes should reduce their size, and they look ok to me!

![image](https://user-images.githubusercontent.com/2874150/62403244-d0cdc400-b583-11e9-98a6-748a1dd2199c.png)

**Comment by musicalentropy** [comment]
Oh my bad, the size is reduced indeed, everything is fine !
