### ISSUE TITLE
Bug removing all the starting equipment

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#482]
I have started the 2nd episode of the Warrior (the one with the curse effects and the battle axes not upgraded but upgraded), and I quit the game during the first fight. When I restarted the game, I was supposed to be able to continue from where I stopped, but then I wanted to look into my equipment, and everything was gone !

**Comment by lcenine** [comment]
Just had the same thing happen with Robot. Quit on floor 1. On continue no equipment.

![image](https://user-images.githubusercontent.com/40739964/62376154-ff10bc80-b50d-11e9-99e9-c84a1461bace.png)

**Comment by TerryCavanagh** [comment]
Investigated this a little: this seems to be related to continuing a game after watching a cutscene.

To replicate:
 - Delete your save files from appdata/roaming/terry cavanagh games/diceydungeons
 - Open the progress editor (press escape on the title screen, and hold Left Shift, then click Progress editor, and select the last button, progress editor), 
 - Set Warrior and Thief to played, like this:
![image](https://user-images.githubusercontent.com/2874150/62463669-7d759480-b782-11e9-89b0-6a910c1de13f.png)
 - Start a game as Robot and watch the cutscene.
 - Immediately quit, then from the titlescreen, load your saved game
 - You will have no equipment.
 - If you try a second time, this won't happen. It seems to be related to viewing the cutscene.

**Comment by mrcdk** [comment]
Fixed
