### ISSUE TITLE
Skeleton ruleset reapplies on loading a save game.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#485]
When loading a save with Skeleton Bonus Round it reapplies the ruleset leaving you with negative dice.

![no_dice2](https://user-images.githubusercontent.com/40739964/62383053-f7a4df80-b51c-11e9-80bc-248ea3c2ba83.jpg)
![no_dice](https://user-images.githubusercontent.com/40739964/62383058-fbd0fd00-b51c-11e9-892f-8ba67f896b9a.jpg)

**Comment by mrcdk** [comment]
Fixed
