### ISSUE TITLE
Reconsider the weakened forms of Burning Light, Ice Shard, and Electric Shock

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#486]
In isolation, they appear fair - but when the Witch has them equipped, and then gets hit for more than 1x Weaken, the fight suddenly becomes a lot more troublesome, and disproportionally so in comparison to other classes.

**Comment by onetruepurple** [comment]
Not more than a minute after I post this:
![image](https://user-images.githubusercontent.com/2095534/62384219-18d3f300-b552-11e9-9003-0179e7afeb1a.png)

**Comment by TerryCavanagh** [comment]
Fixed! All three now become MAX3 slots instead when downgraded.
