### ISSUE TITLE
Consider making Boomerang+ backfire for 4 rather than 3

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#491]
It's common for the Warrior to find two Boomerangs, and 24 damage at the cost of just 6 is a little strong.

**Comment by onetruepurple** [comment]
Case in point
![image](https://user-images.githubusercontent.com/2095534/62387333-9996ed00-b55a-11e9-909d-d1b176cda246.png)

**Comment by TerryCavanagh** [comment]
I like your suggestion on the discord of removing it from the shops, and will do that. I think 1 extra damage on the upgrade probably isn't going to make much of a difference, though!

**Comment by onetruepurple** [comment]
https://cdn.discordapp.com/attachments/423894814124146689/610920600969412608/unknown.png

**Comment by onetruepurple** [comment]
Northernlion has successfully changed my mind here
