### ISSUE TITLE
Bad starting items

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#497]
Singularity and basically anything, singularity sucks
Capacitor and Pea Shooter

**Comment by paceheart** [comment]
Now that Pea Shooter+ does 4 damage, it's a fantastic countdown item once upgraded. even though it sucks as a starting item, I might pick it for its upgrade potential.

**Comment by TerryCavanagh** [comment]
Fixed.
