### ISSUE TITLE
Simplify Sneezy

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#498]
The current version is a too-clever solution to the problem of wanting to reduce their max damage without putting a MAX limit on Sneezy. Try to figure out a way to make them work with just Sneeze and one other (ideally very simple) card.

**Comment by hunky-dory** [comment]
One of the virtues of Sneezy's current layout that might need to be transposed is that the four spikes provide cover for the Sneeze card from shock builds. If you fight 3-item Super Sneezy with any sort of shock of build, it's maybe a little too easy to completely shut them down.

**Comment by TerryCavanagh** [comment]
Fixed 😅
