### ISSUE TITLE
Make "very rare" remix rules less rare

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#499]
I think you should probably get a very rare remix rule on between 50% and 33% of runs. Right now it's 1 in 8.

**Comment by onetruepurple** [comment]
Wherein terry again underestimates how many people will be actually finding the 1/8 rules every day after release ;-)

**Comment by TerryCavanagh** [comment]
True, but I still think it's better from an individual player perspective that these show up a little more often!

**Comment by onetruepurple** [comment]
Maybe I'm misunderstanding - do you mean they would be called more often? Or they woulld just have a higher *chance* of appearing?

**Comment by TerryCavanagh** [comment]
Yep - so when you play a round, instead of having a 1/8 chance of getting one of the veryrare remixes, you'd have a 1/3 chance, say.

**Comment by TerryCavanagh** [comment]
I've tweaked this for v1.9 and am looking forward to seeing how it goes! When rare rules are chosen now, some common rules are removed from the list (this was diluting the possibility of seeing rare rules).
