### ISSUE TITLE
Game freeze when entering upgrade station

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#502]
```
I clicked on the anvil on the map and my game froze for about a
second before Ned showed up.
```

**Comment by mrcdk** [comment]
I've been not able to reproduce this. It's probably because the game loads the backgrounds in the transition and they may take a while to load if your computer is busy. We are using ATF textures now which are faster to load so this shouldn't be a problem anymore.

**Comment by TerryCavanagh** [comment]
Closing!
