### ISSUE TITLE
Misc audio comments from beta testers

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#507]
```
after fight music is way too loud
```
```
I really like the audience sound effects when using equipment!
```
```
The walking noise sounds like logs being hit together or somtehing
```
```
The battle music in this fight with Stereohead is particularly bumpin'
```
```
The battle music in this fight with Stereohead is particularly bumpin'
```
```
I think the battle start sound may also be too loud. 
```
```
and some sound effects were a bit quiet for me
```
```
I love that the Jester talks exclusively in haha's and hoohoo's
```
```
is the low health ticking sound supposed to be playing in the shop?
```
```
Hm, there's still no sound for socketing/unsocketing equipment
```

**Comment by ncrecc** [comment]
The "OOH!"s from high-damage cards get a bit obnoxious, maybe make it a random cheering sfx rather than the same ooh every time?

**Comment by ncrecc** [comment]
The songs themselves seem to be mastered kind of weirdly, like how the former lead instrument in combat1 is now just barely audible.

**Comment by ncrecc** [comment]
Ned's music can be pretty easily desynchronized with him hammering the sword if you minimize the game for a bit, or by leaving and re-entering the anvil.

**Comment by ncrecc** [comment]
Going by ear some sfx seem to play after a short delay, such as poison damage and plasma blaster/ray gun

**Comment by ncrecc** [comment]
Music seems to be a lot quieter than before the funk overhaul in general

**Comment by ncrecc** [comment]
Win music seems *too* quiet now, compared to battle music

**Comment by ncrecc** [comment]
Voiceovers in-battle seem to be drowned out by music

**Comment by ncrecc** [comment]
The shock sound on placing a die in a slot is rather jarring

**Comment by TerryCavanagh** [comment]
Fixed!
