### ISSUE TITLE
Suggestion: make Level Up progress more visually digestible

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#52]
1. The speed at which the bar fills up makes it hard to keep track of how much EXP you started and ended with. Maybe the newly filled slots on the meter should display in a different colour from the already filled ones?

2. If you earn more EXP than you need to level up, it's not clear that the spare EXP carries over:
https://gfycat.com/ThickBlackandwhiteGaur

**Comment by TerryCavanagh** [comment]
I thought about doing this for a while, but probably not going to happen at this point!
