### ISSUE TITLE
The way Lady Luck and human Jester spontaneously disappear in the intro cutscene when the panel turns is a bit jarring

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#520]
Also in the episode ending cutscenes

**Comment by ncrecc** [comment]
Oh, and Baby Squid

**Comment by TerryCavanagh** [comment]
Oh, yep, it is! Unfortunately, it's too late for me to get this one fixed, so I think I just need to live with it as is :(
