### ISSUE TITLE
Add that "custom episodes" trapdoor to episode selection screens

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#523]
terry: I'm thinking that a trapdoor gives you access to modded episodes, maybe!

Also perhaps add an option to the character selection screen to let you choose a modded character

**Comment by TerryCavanagh** [comment]
We don't have trapdoor art unfortunately, but I think we added arrows for multiple "pages" that I'm not sure I've ever seen in a mod?
