### ISSUE TITLE
[rc3] Wizard's spells aren't named consistently

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#526]
Playing Thief PU, the Wizard's spells are currently named:

- `Freeze Spell?`
- `Flame Spell`
- `Poison Spell`
- `Thunder Spell`
- `Teleport Spell?`
- `Hall of Mirrors`

The question marks are inconsistent.

**Comment by ncrecc** [comment]
Cards that need to be reworded are given ? variants. Otherwise they remain the same.
