### ISSUE TITLE
Parallel Universe: ¿Cursed? dice-giving items still give you the dice, but at the top of the screen

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#53]
eg:
![gif](https://giant.gfycat.com/UnhealthyFairBrahmancow.gif)
https://gfycat.com/UnhealthyFairBrahmancow
Is it supposed to be giving your opponent the dice?

**Comment by sstangl** [comment]
Still occurs in v0.6.

**Comment by sstangl** [comment]
Furthermore, the dice appear to float above the screen: if you click "Preview Enemy Moves," these newly-given dice do not change location.

**Comment by ncrecc** [comment]
[1:08 PM] terry: the game doesn't put them in your dicepool, it puts them in the enemy dicepool
[1:08 PM] terry: the bug here is technically that you can use enemy dice at all (which shouldn't be displayed anyway)

**Comment by ncrecc** [comment]
Resolved in 1.9
