### ISSUE TITLE
[rc2] 'Roll 10 1s in a Row' challenge wasn't satisfied by Sneeze+ use

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#533]
In the Finders Keepers Thief episode, I ended up with Sneeze+ and was able to use it twice with 5-6s on a number turns thanks to the Hook limit break. In theory, this should have triggered this challenge, but it doesn't seem to have done so.

**Comment by TerryCavanagh** [comment]
Fixed!
