### ISSUE TITLE
Consider making Toxic Ooze a rare PU exclusive instead

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#535]
Adding poison on 6 is probably the least interesting "X on 6" action, as it's just more damage applied.

However, Poison? changes this radically, but Toxic Ooze is not available in PU, and has fairly low odds of popping up in Bonus Round.

Inflicting Poison? by 2 each round would be an interesting, but not overly strong action against monsters.

This could even fit into #275 and #317 nicely.

**Comment by ncrecc** [comment]
This would make Claw and Blight in non-pu Warrior even more niche.

**Comment by onetruepurple** [comment]
I guess this didn't happen.
