### ISSUE TITLE
Consider duplicate versions of certain items in Inevitability of Rust

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#538]
Multi-use (Spanner, Ray Gun) and once-per-battle (Flamethrower, Crystal Sword, ?) items are not fully working under the Rust rules. To avoid implementing workarounds like "multi use items now have AxB uses", you could implement duplicate versions of those items - i.e. `Spanner@Rust` - that would normally be single-use, but would be multiple use in Rust.

**Comment by TerryCavanagh** [comment]
This is a decent solution, but for launch I'm just disabling all multi-use and once per battle rust items.
