### ISSUE TITLE
When backpack is accessed from the Upgrade Screen, Equipment and Inventory are aligned too far left

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#54]
eg:
![Screenshot 2019-05-12 at 18 40 42](https://user-images.githubusercontent.com/48322734/57586040-9fdf7500-74e7-11e9-9a69-2fac0b7abf8c.png)

**Comment by TerryCavanagh** [comment]
Fixed!
