### ISSUE TITLE
Implement character animations on episode selection

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#553]
Use the animated characters from the cutscenes for character selection instead of the still images.

Use the alternate, "worried" frames instead of the usual one in the "endgame" phase of the game, as seen here:

![image](https://user-images.githubusercontent.com/2874150/62414944-2359bf80-b61a-11e9-8d92-a16e354060a5.png)

(i.e. once `ProgressTracking.isunlocked(char.name + "_atremix")` is `true`.)

**Comment by mrcdk** [comment]
Fixed
