### ISSUE TITLE
Combat and Background Audio Disappear on Continue.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#558]
To replicate, descend to a new floor, immediately quit to title (as in don't encounter anything)  then resume and sounds will be gone.

I had all sound/music on Floor 1 and  when initially reaching Floor 2. On a quit to title and resume, no overworld or combat music was present on Floor 2, just soundfx, victory music and shop sounds. This behavior continues as you descend to lower floors.

Closing and restarting DD does not seem to  fix the issue. Starting a new game does, so it probably has something to do with the save file.  

[continuesave.zip](https://github.com/TerryCavanagh/diceydungeonsbeta/files/3464137/continuesave.zip)

https://drive.google.com/file/d/1w2HTZaaoMf-2MaxrOkbHFGQZEXVba40i/view

**Comment by mrcdk** [comment]
Fixed
