### ISSUE TITLE
Sound doesn't come back when you switch audio output, or when laptop unsleeps/unhibernates/unHDMIs

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#56]
I left my game up for an hour or so, switched tabs and whatnot, and when I came back to it there were no sounds. Other tabs are making sound just fine, but Dicey makes no sound. I went to the options screen, messed with all the sliders, still no sound.

Oh! Maybe it happened when I unplugged it from HDMI. The sound was coming through the TV, and maybe it didn't notice that I want it to come out of the laptop speakers now? I plugged in headphones and unplugged them but that didn't fix it either.

**Comment by paceheart** [comment]
Quit to Title didn't fix it, but Quit, reload, and Continue did. Continue worked, yay!

**Comment by paceheart** [comment]
This still happens in the release candidate. I'm playing with my bluetooth headphones, then I power them off, and all the other sounds on my PC start coming out of my computer speakers, but Dicey is silent. I power my headphones back on and all my other sounds switch to headphones, but Dicey remains silent, except for F12 Screenshot which does make a camera-flash sound. It's not the most critical bug, but it is a bummer to have the second half of the final boss fight (and cool ending music/voice if that's ready yet) be silent, because I don't want to save and quit and lose my mid-battle progress.

Maybe you could make it so that when you go to the options menu, or change any of the audio settings, it checks the audio output source or reinitializes it or whatnot?

I imagine this might come up if a streamer wanted to start streaming in the middle of a game and switched their audio from speakers to stream, they would have to save-quit-continue to reinitialize the audio.

**Comment by TerryCavanagh** [comment]
Might not be much I can do about this one, I think
