### ISSUE TITLE
Witch Card Size Incorrect  - Expect The Unexpected.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#564]
![expect-the-unexpected](https://user-images.githubusercontent.com/40739964/62416512-26e54a80-b60a-11e9-8c61-0b5a76ce9fa4.jpg)

![expect-the-unexpected2](https://user-images.githubusercontent.com/40739964/62416570-17b2cc80-b60b-11e9-8fd3-ac46cbc009d0.jpg)

**Comment by onetruepurple** [comment]
(Lady Luck spells should not be appearing in that slot)

**Comment by TerryCavanagh** [comment]
Fixed.
