### ISSUE TITLE
[rc0.2] [save bug] Challenges completed pre-continue won't be shown on the post-episode Challenges completed list

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#567]
Just to clarify: the completed Challenges are unlockable and will have the flashing 'New!' on the Challenges menu interface, you just don't get any notification that they've been unlocked. If you complete a challenge pre-continue and post-continue, only the post-continue one will be included in the end-of-episode list.

To reproduce:
1. Meet conditions of challenge that can be completed mid-episode
2. Return to menu
3. Continue game
4. Complete episode
5. You won't receive a notification that the challenge has been beaten

**Comment by TerryCavanagh** [comment]
Ah, that's ok I think.
