### ISSUE TITLE
Dice about to be burnt should be instantly burnt if the mouse hovers over it

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#568]
That would disallow you from cheating like this:
![crooce](https://user-images.githubusercontent.com/11216597/62417282-dbd33380-b619-11e9-81e7-f86b5a484e20.gif)

**Comment by ncrecc** [comment]
And locked dice should be immediately locked on hover I guess. Haven't had the opportunity to try placing a locked die in a card before it locks yet.

**Comment by TerryCavanagh** [comment]
Fixed this!
