### ISSUE TITLE
Flaming Sword doesn't work right with non-robot classes

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#569]
This is fairly low-priority since you can't get flaming sword as a non-robot class except through CfB robot or Expect the Unexpected (from what I'm aware). The dice you have at the start of your turn don't get burnt, and dice are only burnt after they're manipulated (e.g. with Combat Roll)

**Comment by TerryCavanagh** [comment]
Fixed!
