### ISSUE TITLE
a lot of enemies are off-center in the beastiary

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#571]
warlock is off-center:
![image](https://user-images.githubusercontent.com/19874772/62418394-d2979600-b61c-11e9-8ad8-ac6dbd25a3de.png)

**Comment by mothbeanie** [comment]
this also applies to cowboy (albeit, mildly),
![image](https://user-images.githubusercontent.com/19874772/62418430-7aad5f00-b61d-11e9-80bd-30d7e2549eff.png)
baby squid,
![image](https://user-images.githubusercontent.com/19874772/62418440-9a448780-b61d-11e9-9baf-d66e1b8aa20a.png)
sticky hands,
![image](https://user-images.githubusercontent.com/19874772/62418448-ac262a80-b61d-11e9-938c-a17f3d6db23b.png)
marshmallow,
![image](https://user-images.githubusercontent.com/19874772/62418453-c2cc8180-b61d-11e9-9454-24a674e41444.png)
stereohead
![image](https://user-images.githubusercontent.com/19874772/62418455-ccee8000-b61d-11e9-9c19-f8f15b6da87d.png)
wizard
![image](https://user-images.githubusercontent.com/19874772/62418456-d2e46100-b61d-11e9-8f9f-aadb773c110e.png)
sneezy
![image](https://user-images.githubusercontent.com/19874772/62418458-d972d880-b61d-11e9-955e-8683ed0d2ec7.png)
and keymaster
![image](https://user-images.githubusercontent.com/19874772/62418462-e42d6d80-b61d-11e9-993c-5a9b431d4c09.png)

**Comment by TerryCavanagh** [comment]
Went through all of these and fixed them up 👌
