### ISSUE TITLE
Pace's thoughts on Parallel Universe

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#58]
Parallel Universe: 1-0

Two suggested rephrasings:
Lucky Roll: Reroll dice, get a higher value than before
Nail Bat: You lose 1hp each turn
because it wasn't clear to me initially who would be losing the hp

I thought Frozen? was bugged because it turned my dice into 2 2 2. Nope! I just rolled 3 3 3, apparently!

Agh, the new equipment is awesome and/or hilarious!
Half Moon Charm! Ha!
Battering Ram is cool!
Nail Bat+ is a weak upgrade.

Whoa, Super Hothead and Super Dryad in one run, yikes!

I found a Last Stand in a chest when I already had one. That's no fun.

Ooh, Flying Skull! Exciting! Aw yeah, Flying Skull+ was killer against Aoife! Win!

I enjoyed the heck out of that episode! It really deserves to be a full-on New Game Plus mode, not just an episode. It's got such amazing replay value!

**Comment by TerryCavanagh** [comment]
Doing an issues clean up at the moment and getting a little nostalgic re-reading these little write ups. Thanks again for everything!

**Comment by paceheart** [comment]
It's been a pleasure! I'm getting nostalgic too seeing all these github messages! I had such a great time playing and testing and hanging out with you and the gang. I haven't been on discord at all lately, so I'm out of the loop - please reach out to me next time you've got a new game for me to beta-test!
