### ISSUE TITLE
When you fight Jester in elimination round, their equipment isn't upgraded

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#581]
It's upgraded on Turn 1, but when Jester switches equipment, they get regular equipment instead of upgraded equipment.

![Dicey Dungeons Aug 04 11-35-03AM robot elimination round vs jester non-upgraded equipment](https://user-images.githubusercontent.com/38589027/62427725-0c63ad80-b6ac-11e9-8c07-a280ead6d110.png)

**Comment by TerryCavanagh** [comment]
UFFF. Yes, this is probably how it should work, but I haven't thought about Elimination round balance for the Jester at all. Maybe it's better to just prevent Jester from showing up in this round (and Bonus Round too, probably?)

**Comment by paceheart** [comment]
I have, so far, successfully avoided spoilers for how to unlock the Jester, since I'm (mostly) trying to simulate the progression of a new player. But if it has something to do with fighting the Jester, then I suggest _not_ preventing Jester from showing up in Elimination Round or Bonus Round, because that would be frustrating for players who are trying to unlock the Jester. For example, if I unlock all 5 characters and then decide to do all the Warrior episodes next, I do 2, then 3, and I still haven't unlocked the Jester, I might play Warrior 4 (Elimination Round) over and over again, hoping that that will unlock Jester. If it has nothing to do with fighting the Jester, then sure, whatevs (:

**Comment by TerryCavanagh** [comment]
Hmm. I suppose it's not the end of the world if Jester shows up in this mode. It's harder, but it should be ok!

No spoilers, but do you remember (even roughly) what your episode progression is? i.e. What episodes you've played, and in what order? Also, do you remember how you win/losses against the Jester have gone? Have they beaten you a few times?

**Comment by paceheart** [comment]
I've only encountered Jester once, and I won. The dialogue was great.

After unlocking all 5 characters, I got impatient and used Progress Editor to input some of my win-loss records from my notes, so I may have messed up the Jester unlock. I'll keep playing and find out!

![20190805192138_1](https://user-images.githubusercontent.com/38589027/62502690-9c395280-b7a5-11e9-8172-a92385e1dc87.jpg)
