### ISSUE TITLE
[suggestion] Allow players to override a click on map screen

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#589]
Occasionally the game will let me override a click (as in the end of the gif), but for the most part, it seems like once you've clicked somewhere, there's no way to back out.

![gif](https://giant.gfycat.com/SpotlessSelfreliantCats.gif)
HD: https://gfycat.com/spotlessselfreliantcats

**Comment by TerryCavanagh** [comment]
This actually caused problems when we tried to implement it, and for the most part I think the current implementation is fine. So, not planning to change at this point!
