### ISSUE TITLE
Consider loosening up the requirements on unlocking Backstage

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#594]
The ideal state of affairs is that in the final game, nobody will dislike an episode enough to feel compelled to skip it - but considering the very varied episode rankings in the beta channel, it already may be too late for that (i.e. even the best episodes will have people who don't like them).

What if Backstage was unlocked not by completing all 36 episodes, but by beating all Bonus Rounds?

This probably sounds like a radical drop, but it's actually not - you need to play at least 4 episodes per character to unlock Bonus Round. With those 4 and Bonus Round beaten, that would be "just" 30 episodes to beat.

This would make the endgame slightly more attainable for the average user, while not at all spoiling the experience for a completionist player.

**Comment by paceheart** [comment]
I like this idea. Loosen the requirements to reach the ending, so more folks get to experience the awesomeness of Backstage, and you've still got achievements and Collection to satisfy the completionists.

**Comment by TerryCavanagh** [comment]
Yep, I think I'm going to do this 👍
