### ISSUE TITLE
Uptick generator issue

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#595]
Other thief episodes work fine, new robot episode also works fine

**Comment by ncrecc** [comment]
Uh, I tried it again and it worked fine. It didn't work the first two times I tried it (one of which was after the actual cutscene) but now it works?

**Comment by ncrecc** [comment]
[6:40 PM] terry: Ah! replicated it
[6:41 PM] terry: There must be a crash in the generator
[6:41 PM] terry: great, gonna fix this immediately

**Comment by TerryCavanagh** [comment]
Fairly certain this is fixed, but it's one where it's hard to be sure. If it happens again let me know!
