### ISSUE TITLE
Locked? (Lockpick!) works on the first dice, not the highest dice.

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#6]
Was fighting Loud Bird - he rolled a 1, 6, 3, 1. Locked? activated on his rightmost 1 (the "first" die to the enemy) and split it into 2 ones.

**Comment by TerryCavanagh** [comment]
Yep! Looks like it wasn't targetting the highest dice like it should have. I've changed the Lock? behaviour now, though, so closing!
