### ISSUE TITLE
Reduce? blocks self-inflicted effects

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#60]
Using Thick Skin+ gives you X Shield? and Reduce?. Using Dark Hedges to gain 5 Thorns? blocks one of them, and you get 4 Thorns? as a result.
Having something like a "Positive" column in statuseffects.csv could help

**Comment by TerryCavanagh** [comment]
Ah! Fixed, thanks :)

**Comment by TerryCavanagh** [comment]
`Having something like a "Positive" column in statuseffects.csv could help`

(Yeah, I do need to fix this for real at some point, or it'll come up with people do custom status effects)

**Comment by paceheart** [comment]
Looks like you missed one - In Thief PU, I borrowed Beatrice's Flight?, and my Reduce? blocked the self-inflicted Dodge?.

![Dicey Dungeons Aug 11 06-43-19AM reduce](https://user-images.githubusercontent.com/38589027/62834585-81326c80-bc03-11e9-9e5c-316533898484.png)

![Dicey Dungeons Aug 11 06-44-30AM blocked dodge](https://user-images.githubusercontent.com/38589027/62834589-90191f00-bc03-11e9-95c4-ee4401a4c950.png)
