### ISSUE TITLE
Giving a huge amount of size 1 items crashes the game, while giving size 2 items doesn't

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#601]
`for (i in 0...30) giveequipment(~Bump~);` will crash
`for (i in 0...30) giveequipment(~Hammer~);` will not crash

**Comment by TerryCavanagh** [comment]
I think a crash is probably the expected result with trying to do something like on a normal equipment layout - really it's just weird that the game *doesn't* crash with the size 2 items
