### ISSUE TITLE
Vertical alignment of [icons] with Londrina Solid typeface is out of whack

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#602]
![Screenshot 2019-08-06 at 17 33 23](https://user-images.githubusercontent.com/48322734/62559567-226f9a80-b873-11e9-9041-e75ffbec9afb.png)
![Screenshot 2019-08-06 at 17 53 20](https://user-images.githubusercontent.com/48322734/62559580-256a8b00-b873-11e9-94e0-9b8ef7a47faa.png)

**Comment by TerryCavanagh** [comment]
Fixed!
