### ISSUE TITLE
Game closes when pressing F12 (screenshot key on Steam)

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#608]
I've had a report from a French journalist that the game crashes when attempting to take a screenshot. Locale issue? Not sure, but crashes are very bad, especially from journalists attempting to take screenshots :(

**Comment by mrcdk** [comment]
This looks like a Lime issue with its FileDialog and I don't really have the time to look into this before release. We have 2 choices, disable the save file dialog and save the screenshot directly or disable the screenshot functionality on Steam because it already has it built-in.

**Comment by TerryCavanagh** [comment]
Ok, yep, done - since Steam has it's own screen functionality we can just turn off the game's one completely for steam builds.
