### ISSUE TITLE
Jester's Back up cards have some wonky image alignment

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#61]
![Screenshot 2019-05-16 at 19 43 39](https://user-images.githubusercontent.com/48322734/57879583-c289ca80-7814-11e9-8c7a-81e99af3bb56.png)

![Screenshot 2019-05-16 at 19 58 51](https://user-images.githubusercontent.com/48322734/57879775-23190780-7815-11e9-87d5-190aa19126a6.png)

What are they scared of?!

**Comment by TerryCavanagh** [comment]
Fixed!
