### ISSUE TITLE
Double quotes are screwy in card description

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#614]
(ignore this initial post - scroll down)

**Comment by TerryCavanagh** [comment]
Oh, csvs are really bad at double quotes. But maybe try escaping them, with `\"`?

**Comment by ncrecc** [comment]
Turns out my csv editor *wasn't actually inserting double quotes* - instead replacing each instance of " I type with “ or ”. So that was a different problem entirely.

It still doesn't play nicely with actual double quotes, though:
![image](https://user-images.githubusercontent.com/11216597/62643902-ff96c200-b916-11e9-8f1b-57a03d6fa20d.png)

**Comment by TerryCavanagh** [comment]
Hmm. Does [quote] work here?

**Comment by ncrecc** [comment]
So it does!
