### ISSUE TITLE
Some usable buttons are styled like a used button(dotted outline).

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#619]
It just felt a little odd to press the "Something Else" button  after seeing the dotted outlines  being used for things that you can no longer press. 

![inv_used](https://user-images.githubusercontent.com/40739964/62642992-e725a800-b914-11e9-98d3-b9f956c862f0.jpg)

OneTruePurple mentioned it was also the button on the "Switch Fighter" button during the Finale
: 
![unknown](https://user-images.githubusercontent.com/40739964/62643336-c0b43c80-b915-11e9-9fe7-27145a193a18.png)

**Comment by TerryCavanagh** [comment]
Fixed both of these. If you spot anymore, please let me know!
