### ISSUE TITLE
Tazer+'s description says it does the wrong type of damage

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#621]
![image](https://user-images.githubusercontent.com/19874772/62676416-a3a45b80-b95f-11e9-95d7-88e877be35e5.png)

![image](https://user-images.githubusercontent.com/19874772/62676421-a7d07900-b95f-11e9-95cf-34f341dfafe7.png)
(Tazer+ should be Do [shock]<d6> damage!)

**Comment by ncrecc** [comment]
Maybe make tazer+ max 5 as well? (to be consistent with claw/claw+)

**Comment by mothbeanie** [comment]
+1 to the above, i basically never upgrade tazer but if it was like claw i would

**Comment by TerryCavanagh** [comment]
Fixed (both!).
