### ISSUE TITLE
Super level 4 enemies (technically level 5) never show up

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#625]
Like, ever. I don't think this is just me being unlucky, I have not seen a single super level 4 enemy (e.g. super snowman, super wicker man) on any run ever

**Comment by TerryCavanagh** [comment]
This is intended - they're basically just not implemented - a loose end in the design :( Maybe I'll revisit the idea for daily challenges down the road, or something.
