### ISSUE TITLE
Mechanical Leg's description doesn't change if you get it through Expect the Unexpected

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#626]
![image](https://user-images.githubusercontent.com/32357485/62775454-98f0e000-ba9f-11e9-9f48-fed605146a72.png)

Its description stayed at 0 even after I used dice and other items. However, it still did the correct amount of damage.

**Comment by TerryCavanagh** [comment]
Fixed, sort of (this isn't a valid witch spell anymore).

I'm gonna start marking issues that I've closed with these kind of "that can't happen anymore" fix with a special label, so that maybe later I can come back and fix them properly.
