### ISSUE TITLE
Winning a fight with 0 health stops the music for at least the next floor

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#634]
To repeat:
- Take a pre-level up fight with Boomerang or against an opponent that has thorns
- Win the fight in a way that leaves you with 0 health
- After level-up, the music will stop playing in the map and during fights.

Some events seem to cause the music to return. Moving from floor 1 to floor 2 didn't fix the issue, but moving from floor 2 to 3 did.

**Comment by hupfen** [comment]
Reproduced on rc v0.7

**Comment by TerryCavanagh** [comment]
Fixed!
