### ISSUE TITLE
Mimic spawns unupgraded items in Hard mode

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#64]

**Comment by paceheart** [comment]
Reproduced in RC5. Mimic had an upgraded item on Turn 1, but on successive turns, it's just regular stuff.

Thief Elimination Round:
![Dicey Dungeons Aug 10 02-05-28PM mimic got de-upgraded](https://user-images.githubusercontent.com/38589027/62826864-2e5fa300-bb78-11e9-9413-1f73135f045f.png)
![Dicey Dungeons Aug 10 02-06-06PM mimic got de-upgraded 2](https://user-images.githubusercontent.com/38589027/62826865-30296680-bb78-11e9-91b1-4633be300e5d.png)

**Comment by onetruepurple** [comment]
Resolved by launch.
