### ISSUE TITLE
Lady Luck's Judgement phase lets you use the same character for all 3 turns

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#642]
For example, I just got:
- green things (cactus) take 1 damage
- green things take 1 damage, hat-wearers take 1 damage (cactus)
- green things take 1 damage, hat-wearers take 1 damage, plants take 1 damage (still cactus)

**Comment by TerryCavanagh** [comment]
That's ok, I think! It's one of the intended paths that can happen in rare situations, and it still works design wise even if it's not as good.
