### ISSUE TITLE
Going back to character select after winning Backstage and choosing another character caused a crash

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#644]
![image](https://user-images.githubusercontent.com/2095534/62819467-170fbe00-bb56-11e9-9ef7-d1f7ba9ca113.png)

**Comment by TerryCavanagh** [comment]
same as https://github.com/TerryCavanagh/diceydungeonsbeta/issues/638, will close both when I fix this today :marshmallow:

**Comment by paceheart** [comment]
Here's a crash log of this in case it helps.
[_error.txt](https://github.com/TerryCavanagh/diceydungeonsbeta/files/3489367/_error.txt)

**Comment by mrcdk** [comment]
Fixed
