### ISSUE TITLE
Support Chinese and Korean Logos on the title screen

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#645]
For chinese and korean, we're using a localised logo on the title screen - however, our new title screen is an animation that embeds the english logo!

Easiest fix to this is probably to just turn off the english logo layer in the animation, and hard code detect those languages and use the localised versions for them.

**Comment by TerryCavanagh** [comment]
Chinese logo:

![logo](https://user-images.githubusercontent.com/2874150/62821567-ceb0ca00-bb6e-11e9-88d4-09d30148e395.png)

(will post Korean once it's ready)

**Comment by mrcdk** [comment]
Chinese done

**Comment by mrcdk** [comment]
Korean done
