### ISSUE TITLE
Falling off the map when loading a save

### ISSUE THREAD

**Issue by Classified9999** [TerryCavanagh/diceydungeonsbeta#648]
When loading a save after returning to main menu while the 1st inventor cutscene played, my character spawned off the map and the cutscene was skipped. There was no way to get back on the map, and when reloading the save, the same thing happened.

**Comment by TerryCavanagh** [comment]
Sounds like quitting to title during an intro cutscene and then resuming the save in general causes problems. We should probably just delete the save in these cases, or only store a save after a player has made an action in an episode.

**Comment by mrcdk** [comment]
For now I disabled the `Go back to title` button in cutscenes, it's not a good fix because users can still close the game and have the same issue but it'll do for launch

**Comment by TerryCavanagh** [comment]
Cool, thanks!
