### ISSUE TITLE
Consider simplifying Mystery Box into a passive like Fuse

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#65]
Since the player can no longer obtain by regular means.

This would also potentially fix #64 by design, if the script was applied to the box itself rather than the Mimic.

**Comment by onetruepurple** [comment]
Alternatively, consider doing what Jackeea did here https://streamable.com/bs3pn

**Comment by onetruepurple** [comment]
Still doable, and would cost nothing really.

**Comment by TerryCavanagh** [comment]
I think part of the appeal of Mimic as an enemy seeing the mystery box as an enemy move, even though it's a little weird and inconsistent with how other things in the game work. A rough design edge, I guess. I think it should stay.

**Comment by onetruepurple** [comment]
Sorry, was unclear - I meant a passive card with no diceslots.

**Comment by TerryCavanagh** [comment]
Ahh, right!

I still think it's fine as it currently is - passives are kind of weird and it'd be weird to see so early in the game I think.
