### ISSUE TITLE
Silence not breaking

### ISSUE THREAD

**Issue by Classified9999** [TerryCavanagh/diceydungeonsbeta#650]
When playing regular inventor, I was silenced. I tried putting a 1 and a 5 into the silence, but only the 5 went in and none of other dice would go in, causing me to be unable to break the silence.

**Comment by TerryCavanagh** [comment]
Hopefully I haven't broken anything here

**Comment by TerryCavanagh** [comment]
Oh, this one has been fixed since v1.7 (longer than it should have been around, but whatever!)
