### ISSUE TITLE
Enemies suicide on my Thorns

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#652]
![Dicey Dungeons Aug 10 08-12-59AM kamikaze gardener](https://user-images.githubusercontent.com/38589027/62823560-f9872800-bb46-11e9-8541-4a9d8a9dbd2e.png)

The 999999 incentive for the AI to kill the player should only be applied if it doesn't also kill the enemy, since a double-kill is a win for the player.

This happened to me in a Finders Keepers run, and I reproduced it in the editor (pictured above). I swear, in that same run, another enemy also suicided on my Thorns when it _didn't_ kill me, but I haven't been able to reproduce it.

**Comment by TerryCavanagh** [comment]
Replicated on main!
