### ISSUE TITLE
Trader crash bug

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#653]
```
Talking to a trader, I took the deal but then going back to her she's
offering the same deal - even though I no longer have the item she's
asking for. Accepting the trade crashed the game.
```

Apparently traders are no longer disappearing as they should. Once you've taken a trade, the trader shop is supposed to vanish from the map. (this playtester doesn't know the game that well and might be slightly confused about the situation)

**Comment by mrcdk** [comment]
I've not been able to reproduce this. The trader is removed after accepting the deal. Either way I tweaked a bit the code to try and avoid possible issues.
