### ISSUE TITLE
Crash bugs lock up a computer when playing fullscreen

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#655]
I think we had this one fixed in the past (it's supposed to change to windowed mode), but seems like it's back:

```
I then can't close the crash screen! It gives the "what a bad roll" message, 
clicking anywhere onscreen minimises the window but it's still there on the 
task bar. Pressing alt+F4 does nothing. Right clicking it in the task bar 
and choosing "close window" does nothing.
```

(tester is on windows)

**Comment by mrcdk** [comment]
The code is still there and it does work but depending on the crash and when it happens the window may be totally locked and won't minimize or do anything. I don't think we can do anything here (apart from solving all the crashes 😅, of course)

I've tweaked the post crash handler so it doesn't have to do much processing, hopefully this alleviates the issue a bit.
