### ISSUE TITLE
Bizarre character scaling on character select screen when selecting backstage then another character

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#656]
![](https://i.frogbox.es/luv)
(if gif isn't showing, go [here](https://i.frogbox.es/luv))

**Comment by ncrecc** [comment]
Related issue: the panels showing info about the characters go up and down rather than flipping around until you trigger this glitch

**Comment by TerryCavanagh** [comment]
Fixed!
