### ISSUE TITLE
Need to remove the word "Episodes" from the episode selection animation

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#660]
![image](https://user-images.githubusercontent.com/2874150/62826971-61785580-bbbd-11e9-8aa1-54a418c5b526.png)

I manually removed the word "Episodes" from the png texture file, but it's still in the ATF textures! (alternatively, we could just hide the layer)

**Comment by mrcdk** [comment]
Fixed
