### ISSUE TITLE
Use separate animations for each door on the episode select screen opening

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#661]
Right now the doors all use the animation of door 3 opening, so they look like they have a 3 die as they open.

**Comment by ncrecc** [comment]
Doors with no dice (doors to episodes you haven't completed) show the 3 when opening as well

**Comment by TerryCavanagh** [comment]
Not planning to do this (though yes, it was a bit lazy)
