### ISSUE TITLE
Lady Luck AI bug: she ended her turn instead of attacking

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#664]
She had the one that's 3x[ ], but only 1 if you have shield. I weakened it to only 2x. She rolled 66666 (what are the odds?) but didn't put a dice into it. I didn't have any shield.

**Comment by paceheart** [comment]
On the topic of Lady Luck AI bugs:

> onetruepurple: also a minor factor, but if she rolls Divine Sword and Cornucopia, and Divine Sword kills you, she never actually uses Cornucopia for the random blessing

**Comment by TerryCavanagh** [comment]
This is one of the Divine weapons, I think! Replicated on the main repo.
