### ISSUE TITLE
Shop occasionally has no music

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#665]
I can never pinpoint when or why this happens :/ - when it does, exiting and re-entering the shop fixes it. Maybe it just happens the first time you visit a shop in the current run or session?

**Comment by TerryCavanagh** [comment]
It's probably something to do with changing sounds too quickly for the game to keep up - if you trigger the change within 0.8 seconds of a fade (say by going to a chest and then quickly going to a shop), it probably doesn't change the parameters correctly. This is very fixable, but might be a post launch thing :(

**Comment by TerryCavanagh** [comment]
Fixed!
