### ISSUE TITLE
Heartbeat sound does not play when at low health in Worse than a Curse

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#666]

**Comment by ncrecc** [comment]
Same with finale but I'm guessing in finale it's intended since you can swap characters?

**Comment by onetruepurple** [comment]
Intentional in both.

**Comment by TerryCavanagh** [comment]
Yep, this is on purpose - definitely the right call for the Finale. I'm not sure if it's right in Worse than a Curse 🤔

**Comment by TerryCavanagh** [comment]
Actually, yep, this is fine as is.
