### ISSUE TITLE
Remove the "Beat a boss in the first turn" achievement from the list

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#667]
I unlocked the challenge but there was no new monster in the gallery present.

**Comment by TerryCavanagh** [comment]
Oh, I removed that. The one about defeating an enemy on turn one is good, but the boss one isn't, I think.

**Comment by onetruepurple** [comment]
Well, then me getting that achievement to show up is a bug. ;-)

**Comment by TerryCavanagh** [comment]
Ahhh! You're right! I need to remove that from the checked achievements completely 👍

**Comment by TerryCavanagh** [comment]
Fixed.
