### ISSUE TITLE
Lopsided level generation

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#669]
Feels like this layout is misaligned to the left

![image](https://user-images.githubusercontent.com/2095534/62834367-43593680-bc4b-11e9-89b3-0b6688bc2452.png)

**Comment by TerryCavanagh** [comment]
YES. This particular grid layout annoys me every time I see it. Gonna remake it before launch! Thank you for the issue!

**Comment by onetruepurple** [comment]
Resolved on launch.
