### ISSUE TITLE
Some items' weakened versions appear identical to normal

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#67]
This applies to:

- Backstab
- Bandage
- Crystallize
- (Divine Rod)
- Fists
- Hacksaw
- (Incoming!)
- (Infestation)
- Knuckle Duster
- Missile Launcher
- Nightstick
- Scissors
- Spare 1
- Spare 2
- Spare 3
- Spare 4
- Spare 5
- Spare 6
- Target Shield

Not listed is Juggling Ball, which has a different description but works identically (already reported on the public github).

**Comment by TerryCavanagh** [comment]
Hey - looking into some of these cases, looks like they might be broken on a case by case basis - but lots of them seem to be working as expected? Could be something that's only failing in certain situations!

One particular bug I could identify here is that the "removereusable" type wasn't working correctly, but I've fixed that now. Leaving this open to review again after v0.17!

**Comment by TerryCavanagh** [comment]
I think this is ok now - have added safety checks in v0.17.2 to catch cases where equipment is identical!

**Comment by onetruepurple** [comment]
RC1:

![image](https://user-images.githubusercontent.com/2095534/62012188-43edc980-b183-11e9-866a-327dab4178cb.png)
![image](https://user-images.githubusercontent.com/2095534/62012197-58ca5d00-b183-11e9-996d-4915337e048c.png)
![image](https://user-images.githubusercontent.com/2095534/62012221-bbbbf400-b183-11e9-9224-e44cb0c147bc.png)
![image](https://user-images.githubusercontent.com/2095534/62012269-5fa59f80-b184-11e9-9e18-35f37583c484.png)
![image](https://user-images.githubusercontent.com/2095534/62012291-a72c2b80-b184-11e9-94fd-5e564fa1170d.png)
![image](https://user-images.githubusercontent.com/2095534/62012336-5406a880-b185-11e9-94a2-ff8e97749599.png)
![image](https://user-images.githubusercontent.com/2095534/62012347-74cefe00-b185-11e9-882a-daa4679a39e5.png)
![image](https://user-images.githubusercontent.com/2095534/62012371-a0ea7f00-b185-11e9-8cdb-6355dede67a5.png)
![image](https://user-images.githubusercontent.com/2095534/62012395-dd1ddf80-b185-11e9-9b0f-f91c2b709440.png)
![image](https://user-images.githubusercontent.com/2095534/62012398-fd4d9e80-b185-11e9-90da-bc4296836f27.png)
![image](https://user-images.githubusercontent.com/2095534/62012399-03dc1600-b186-11e9-8882-66281b35541d.png)
![image](https://user-images.githubusercontent.com/2095534/62012401-0ccce780-b186-11e9-8923-3ded9b69fda5.png)
![image](https://user-images.githubusercontent.com/2095534/62012404-148c8c00-b186-11e9-9fab-bae0d1cf736e.png)
![image](https://user-images.githubusercontent.com/2095534/62012406-1a826d00-b186-11e9-8144-647fabf0e425.png)
![image](https://user-images.githubusercontent.com/2095534/62012409-20784e00-b186-11e9-8585-309b06942d3b.png)
![image](https://user-images.githubusercontent.com/2095534/62012421-40a80d00-b186-11e9-8cd9-3c3af23a7015.png)

**Comment by ncrecc** [comment]
Downgraded spares start burnt when used in-battle. They're supposed to, anyway.
