### ISSUE TITLE
Lock?ed dice don't re-lock if you put all locked dice in multi-slot equipment

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#678]
https://streamable.com/rbb85

It works correctly if you have, for example, 2 Lock? and put 1 dice in a multi-slot item, but if you fully "deplete" your Lock? then the dice are unlocked despite you not "using" the first dice.

**Comment by TerryCavanagh** [comment]
Replicated on the main repo!
