### ISSUE TITLE
Crystallina can end up with 5 cards, one of which lives offscreen

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#68]
Bit of a weird one!

If Crystallina gets the recycle blessing and then triggers one of her Crystallize counters, she will get the randomly generated product of crystallize _and_ the crystallize card will be recycled.

This new crystallize card ends up living off screen during turns but floats on & off again at the beginning and end of the turn. From my case, it wasn't clear whether Crystallina could use the card, as the dice were allocatable to her four onscreen cards.

**Comment by TerryCavanagh** [comment]
Ah, yep, this one is covered by issues on the main repo. Closing!
