### ISSUE TITLE
[rc5] Crash via Change Language

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#680]
I can reliably reproduce a crash by the following procedure:

1. Start Dicey Dungeons.
2. Press Escape.
3. Click the "Language" button.
4. On the language selection screen, press Escape.
5. Select "Back to Title." If all characters were unlocked, they now show as white dice.
6. Click "Play". The game crashes.

The error is:
```
ERROR in callscenemethod(Title,update) static: Null Object Reference, stack=
Called from ProgressTracking.isunlocked (ProgressTracking.hx line 165)
Called from ProgressTracking.isunlocked (ProgressTracking.hx line 141)
Called from state.Title.update (states/Title.hx line 163)
Called from FadeControl.update (FadeControl.hx line 80)
Called from Screen.endrender (Screen.hx line 275)
Called from states.Title.update (states/Title.hx line 275)
Called from Reflect.callMethod
```

**Comment by mrcdk** [comment]
I've disabled the settings in the language selection screen. Fixed.
