### ISSUE TITLE
Nightstick is semantically nonsensical

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#686]
Shock hasn't been Stun for over a year. How did we not notice this???

**Comment by ncrecc** [comment]
Maybe name it Laser or Zapper

**Comment by TerryCavanagh** [comment]
Isn't that Deus Ex weapon with the tazer knockout effect called a nightstick? I think that's what I was thinking of here! Anyway, happy to live with this one as is.
