### ISSUE TITLE
Bear saved game had wrong equipment and a downgraded item.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#688]
Had Upgraded Bear Maul, regular Bear Maul and Roar.

 On continue had 2 normal Bear Mauls and Hibernate.

**Comment by mrcdk** [comment]
Fixed.

**Comment by paceheart** [comment]
Reproduced in RC7. I had Bear Maul, Bear Maul+, Bear Charge+, and Honey, plus Bear Swipe in my backpack. Back to title, then continue, and I've got Bear Maul, Bear Maul, and Bear Roar. After that it stays consistent, but that first step's a doozy.

Maybe it only happens with upgraded items?

**Comment by TerryCavanagh** [comment]
Fixed!
