### ISSUE TITLE
[rc7] Using a dice plays a zapping noise

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#689]
The zapping noise seems very out of place and is probably unintentional? It occurs any time a dice is placed into a slot.

**Comment by sstangl** [comment]
The zapping noise is the shock noise. If I unshock something, it plays the noise twice.

I hear the shock noise every time a dice is used.

**Comment by mothbeanie** [comment]
it sounds especially strange when im putting in a lot of dice at once, like for countdowns

**Comment by sstangl** [comment]
Terry said in-chat that this is now fixed.
