### ISSUE TITLE
Robot: Error animation on hidden used cards can be seen at top/bottom of screen

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#69]
This was with a loadout of three green cards, which exit screen-bottom, and three red cards that exit screen-top:

![image](https://giant.gfycat.com/WindyValuableIndianrhinoceros.gif)
https://gfycat.com/WindyValuableIndianrhinoceros

**Comment by TerryCavanagh** [comment]
Think this one is fixed now!
