### ISSUE TITLE
Snake Eye Charm does nothing

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#694]
I just activated Snake Eye Charm and it did nothing. It ate my dice, flew off the screen, and... nothing. 
![Dicey Dungeons Aug 12 08-38-30PM snake eye charm](https://user-images.githubusercontent.com/38589027/62913528-53ebd880-bd41-11e9-9a77-12e764a95f98.png)
Thief episode 1, RC7.

Snake Eye Charm- also does nothing.

**Comment by TerryCavanagh** [comment]
Fixed. I broke something when I made the change to blind behaviour. Really glad I caught this one, it's super serious - thanks so much @pace212!
