### ISSUE TITLE
Dice character animation in very start of intro ("We present.... [contestant's name]!" followed by silhouette turning into a dice) stops after dice's first line

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#699]
After the silhouette scene it works fine though

**Comment by TerryCavanagh** [comment]
Yeah, this is a slightly annoying one, but I can't fix it without redoing the animation files, which isn't really feasible anymore. Thankfully, it looks somewhat intentional, so I'm happy to live with it.
