### ISSUE TITLE
AI bug: Rat King chooses Rat- over Rat

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#703]
RC7, Turn 1
![Dicey Dungeons Aug 13 06-42-32AM Rat King chooses weakened Rat](https://user-images.githubusercontent.com/38589027/62946493-a35bf400-bd95-11e9-927b-fbcbb84ff39f.png)

**Comment by TerryCavanagh** [comment]
Duplicated on the main repo!
