### ISSUE TITLE
[1.0] if Keymaster's dice is blinded, a different-valued dice can be returned to it

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#706]
I pasted a video in the chat, but GitHub doesn't let me upload WebM.

**Comment by sstangl** [comment]
Here's an image. Note the turn count: 
![Screenshot from 2019-08-13 19-13-59](https://user-images.githubusercontent.com/171223/62987775-a939ef80-bdfe-11e9-8450-d616f2c6ce19.png)

**Comment by ncrecc** [comment]
https://cdn.discordapp.com/attachments/552131784939405332/611005666030518275/keymasterblind.mp4

**Comment by TerryCavanagh** [comment]
Duplicated on the main repo!
