### ISSUE TITLE
[1.0] When a Jester card is hit by Curse, no card is drawn to take its place

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeonsbeta#708]
![Screenshot from 2019-08-14 15-34-53](https://user-images.githubusercontent.com/171223/63058957-58340500-beab-11e9-80c0-09ddd6ba165b.png)

**Comment by ncrecc** [comment]
Duplicate of #136

**Comment by ncrecc** [comment]
This has been fixed.
