### ISSUE TITLE
You can gauge the value of a blind robot dice by how many "cpu increase" sound effects play upon calculating it

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#709]
If you hear 6 ticks, your blind dice is a 6. If you hear 3, your blind dice is a 3. So on and so forth. These tick sounds should be either removed or replaced for rolling blind dice.

**Comment by TerryCavanagh** [comment]
Oh, haha - this got mentioned a lot in comments around launch. I think it's a nice thing to leave in there.
