### ISSUE TITLE
Suggestion: "back to editor" button

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#713]
it'd be super helpful to have "back to editor" button in the ESC menu in an editor battle for when i'm testing a lot of battles/equipment/etc

**Comment by mothbeanie** [comment]
relatedly: default to warrior if no character is chosen when starting a battle, maybe?

**Comment by TerryCavanagh** [comment]
Since launch, I made it so that you immediately leave a battle if you select flee, which I think basically covers this!
