### ISSUE TITLE
Big uh-oh: you can copy Dice Cannon with CfB Inventor, that plus snap means inf. damage

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#714]
![image](https://user-images.githubusercontent.com/11216597/63227101-18259880-c1b1-11e9-8f9e-e8f1584ea3bc.png)

**Comment by ncrecc** [comment]
If reusables or multi-use cards are snapped, they should probably be discarded

**Comment by TerryCavanagh** [comment]
Great! I love this 😄
