### ISSUE TITLE
CfB robot can provide start-of-turn passives that do nothing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#715]
![image](https://user-images.githubusercontent.com/11216597/63227298-bf56ff80-c1b2-11e9-9d4a-0304a25940e1.png)

**Comment by ncrecc** [comment]
Perhaps trigger passive effects as soon as they enter the usable deck, if that doesn't happen already.
I guess the only bug here is that dramatic entrance is in red (indicating it's the first turn and has provided fury) rather than gray. Would be nice for dramatic entrance to treat *the first turn it's available* as the first turn though. Similarly, Plague's effect should trigger immediately once it enters the usable deck and not trigger if it isn't taken out of the next up.

**Comment by TerryCavanagh** [comment]
Fixed!
