### ISSUE TITLE
Grindstone can't raise other Grindstone's durability, if it's duplicated via copyshop

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#716]
Intended or no?

**Comment by ncrecc** [comment]
Grindstone raising durability of grindstones other than itself could be achieved if on execute checked for non-e rather than not being named Grindstone
```
for(eq in self.equipment){ if(eq != e){ eq.totalusesremaining++; eq.animate(~flash~); } }
```

**Comment by TerryCavanagh** [comment]
Hmm, this *was* intended, for better or worse. Otherwise you can get an infinite loop in a kind of tedious way. Probably for the best not to encourage it.
