### ISSUE TITLE
Give Uptick Thief an immunity to Blind

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#719]
Since Blind will almost never affect you in Uptick anyways, as you always know what value your current dice are. (For the sake of modded items that roll blind dice mid-turn this should probably only apply to blind inflicted at the very start of your turn)

**Comment by TerryCavanagh** [comment]
Ah, nah. I see what you're getting at, but I think it's a nice moment for the player to realise "oh, I know what all my dice are, haha", and making Thief immune to blind in this episode would achieve nothing except robbing them of that realisation, so far as I can see!
