### ISSUE TITLE
Some cards' upgrades and their PU versions' upgrades differ, while their non-upgraded versions are alike

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#720]
Echo Blast+ is +1, Echo Blast?+ removes the odd-only restriction

**Comment by ncrecc** [comment]
Snowball+ and Snowball?+ are also different - Snowball+ is +2 whereas Snowball?+ is 2 freeze rather than 1. I thought I put that on a separate issue somewhere but maybe no?

**Comment by ncrecc** [comment]
Shovel+ is weaken on even, Shovel?+ is always weaken

**Comment by TerryCavanagh** [comment]
Ahh, these are ok I think.
