### ISSUE TITLE
UI shakes on overworld if you use spooky fury on boomerang and you get hit twice on the levelup screen

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#724]
![wra](https://user-images.githubusercontent.com/11216597/67604194-f284b480-f748-11e9-805d-2b17727c703d.gif)

**Comment by ncrecc** [comment]
Maybe this also happens with regular fury (when stacked)?

**Comment by TerryCavanagh** [comment]
This happens very occasionally if you win a fight with Boomerang. It's been around for a little while! There's a duplicate of it somewhere in the main issues tracker - probably not gonna get it fixed for Halloween!
