### ISSUE TITLE
Leaving a game and loading it caused a crash

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#726]
![image](https://user-images.githubusercontent.com/32357485/67604948-dac32580-f774-11e9-8dfe-a21b999e0db0.png)

**Comment by JackeeaJ** [comment]
https://pastebin.com/xSvnhNmZ

**Comment by findersjeepers** [comment]
I experienced this crash as well with an identical log.

**Comment by TerryCavanagh** [comment]
I think this one was also due to contamination between modded and unmodded save files, which shouldn't be an issue anymore!
