### ISSUE TITLE
character select visual bug

### ISSUE THREAD

**Issue by mothbeanie** [TerryCavanagh/diceydungeonsbeta#727]
![image](https://user-images.githubusercontent.com/19874772/67606646-e8f25100-f736-11e9-9635-abd5be80ae22.png)
before this, i had an in-progress jester save file appear on the continue screen, but i hit new game.

**Comment by lcenine** [comment]
Also happened to me.

![witch](https://user-images.githubusercontent.com/40739964/67637951-2cbf9480-f8b6-11e9-9fb9-3d8415393825.png)

**Comment by TerryCavanagh** [comment]
I believe this is due to having a continuesave file active in the non-modded version - I've changed it to have a seperate save file, so hopefully this no longer comes up (it's a little hard to test, so I'm crossing my fingers here)
