### ISSUE TITLE
Solenoid appears to start at 0 damage

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#728]
![image](https://user-images.githubusercontent.com/32357485/67609597-85434480-f785-11e9-9462-47c1986935da.png)

**Comment by ncrecc** [comment]
But appears correctly once you enter battle. Do generators have access to setvar?

**Comment by TerryCavanagh** [comment]
Having the generator set the equipment variable seems like a decent solution here, but might make it complicated to track adding items to other episodes in future - something self contained on the item might be better. Will think about it before Monday and hopefully figure out something fairly future proof!

**Comment by TerryCavanagh** [comment]
Yeah uff I'm short on time so I'm just going to cardboard sword/particle accelerator this thing and fix it later

**Comment by TerryCavanagh** [comment]
Fixed (well, enough for Halloween anyway)
