### ISSUE TITLE
Applying Freeze? or Shock? to yourself mid-turn does nothing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#73]
(This can be accomplished with Curse?)

I'm guessing this also applies to regular Shock and Freeze, as well as Poison?, Weaken, Lock, and Lock?. Not sure how Lock? would be applicable mid-turn.

**Comment by ncrecc** [comment]
Applying Burn? to yourself only causes a burnt die to appear once you manipulate a die, e.g. with Combat Spatula (though that might only happen when it's a generic "burn 1 dice" and not "burn this dice" - might be the same with regular burn).

**Comment by TerryCavanagh** [comment]
This is really a modding issue, and with recent versions it is possible to activate status effects like this mid turn with some fancy scripting. Closing!
