### ISSUE TITLE
Electric Whip shocking a 2-slot item with a dice "stored" inside it causes a crash

### ISSUE THREAD

**Issue by JackeeaJ** [TerryCavanagh/diceydungeonsbeta#731]
Against Mummy, I put one of my dice inside Allen Key to stop it from being Haunted. I then used Electric Whip, and Allen Key then got shocked - I saw a frame or two of the animation, and the game crashed.
https://pastebin.com/nzDhmBwe

**Comment by TerryCavanagh** [comment]
And fixed this one too! Thanks.
