### ISSUE TITLE
 Can't continue game. Continue / New Game screen just reloads. No crash report.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#735]
Exited to title screen. 
Tried to continue game a little while later.
Selecting "Continue" just reloads the  Continue / New Game  screen.
Exiting and restarting didn't change the behavior.

**Comment by TerryCavanagh** [comment]
I can't replicate this one, but I think it was probably due to a save file issue I've now fixed. Thanks - closing!
