### ISSUE TITLE
Game unnecessarily loads floor-related stuff when I select a character in the editor

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#751]
Upon clicking Warrior, it loaded for a second and spit this through the console:
```haxe
Dungeon.hx:455: [Slime,Frog,Wolf Puppy]
Dungeon.hx:456: [Pirate,Baby Squid,Dryad,Marshmallow,Wizard]
Dungeon.hx:457: [Sorceress,Haunted Jar,Demon,Yeti,Handyman]
Dungeon.hx:458: [Kraken,Rotten Apple,Dire Wolf,Wisp,Mummy]
Dungeon.hx:459: [Gargoyle,Skeleton,Banshee,Warlock,Cornelius]
Dungeon.hx:460: [Pumpkin Spice,Madison,Enormous Jerk,Drake]
Floor.hx:373: [Wolf Puppy]
Floor.hx:374: [Frog]
Floor.hx:373: [Wizard]
Floor.hx:374: [Marshmallow,Dryad]
Floor.hx:373: [Baby Squid]
Floor.hx:374: [Handyman,Yeti]
Floor.hx:373: [Demon]
Floor.hx:374: [Mummy,Wisp]
Floor.hx:373: [Dire Wolf,Rotten Apple]
Floor.hx:374: [Cornelius,Warlock]
Remixstate.hx:70: set 2_ to [Demon]
Remixstate.hx:70: set 3_ to [Mummy]
Remixstate.hx:70: set 4_ to [Pumpkin Spice]
```
(Enormous Jerk is a test boss, ignore it)
Same thing with Inventor except it leaves out the remixstate parts, and same thing with Witch except it leaves out the remixstate and floor parts.
Trying to select Jester, Thief, or Robot causes a crash immediately.

**Comment by ncrecc** [comment]
Jester, Robot, Thief crash stops if contents of halloweenspecial (except mod info) are removed, so the crash must be related to them not having halloween episodes

**Comment by TerryCavanagh** [comment]
Ah, I left some debug info in - have removed that. The thing with Robot, Thief and Jester crashing the editor is a separate thing!
