### ISSUE TITLE
Pumpkin health sprite looks off center on the overwoldlo

### ISSUE THREAD

**Issue by marlowe-dobbe** [TerryCavanagh/diceydungeonsbeta#754]
Looks like it's hanging to the right a bit and that part of it is cut off in the bottom right?

(This might be my fault! Just wanted to log it here!)

**Comment by marlowe-dobbe** [comment]
Actually it looks like there could be a centering pass on all the new overworld sprites! Handyman and pirate and placed too low on their spots for example!

**Comment by ncrecc** [comment]
Wisp also looks too far to the right

**Comment by TerryCavanagh** [comment]
Did a centering pass on all the overworld sprites, and repositioned the Pumpkin. Let me know if it looks ok in the new build (coming asap)
