### ISSUE TITLE
Don't offer health tonic + polarity flip on the same run

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#756]
One or the other! Health Tonic is a pretty rubbish joke item if it actually works on the player

**Comment by findersjeepers** [comment]
Weirdly enough, I just had Health Tonic + Polarity Flip *not* work for me.

Sequence of events:
* I was fighting Dire Wolf and had been putting dice toward Health Tonic without immediately completing it
* Dire Wolf cursed me
* At the start of my next turn, turn #3, I used my Magic Dice gadget to roll an extra dice
* I activated Polarity Flip 
* I finished the Health Tonic countdown
* Dire Wolf was healed, not me
* "Swap Next Target" status icon did not disappear
* I activated Safety Goggles, and it was cursed
* At this point, both the Curse status icon and the Swap Next Target status icon disappeared

**Comment by findersjeepers** [comment]
I have now also experienced the above bug after being cursed by Banshee, so it looks like it's an interaction between Curse and Swap Next Target.

edit: It looks like it affects all SNT, not just Health Tonic, so I will open a new issue for this: #766

**Comment by TerryCavanagh** [comment]
I just changed this to be a reverse First Aid Kit - that feels better than completely preventing the interaction. Fixed!
