### ISSUE TITLE
Mummy, due to current design, very rarely uses bandage whip

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#758]
Mummy will *never* place odd dice in bandage whip when the haunt cards are available, even if it has enough dice to fill the countdown. (It might place odd dice in bandage whip if the countdown is already low enough that it can be activated by one dice, I haven't checked.)

**Comment by TerryCavanagh** [comment]
Yep, that's fair - I reduced the countdown on Bandage Wrap to 7, and removed the bonus on 5s. Bandage Wrap is a lot more common now!
