### ISSUE TITLE
Sorceress Mutated from Kraken had no items

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeonsbeta#761]
After using the Mutate gadget to transform a Kraken into a Sorceress on my first turn of the fight, the Sorceress had no spells at all. This was borne out not only during her turns but also in the enemy move preview.

**Comment by TerryCavanagh** [comment]
Ahhh I hate this workaround, but I'm just gonna exclude Sorceress from the mutation list for Halloween. For v1.7 I'll come back to it and see if I can fix it properly.

**Comment by TerryCavanagh** [comment]
That workaround is fine. Closing!
