### ISSUE TITLE
Hole Puncher, Shredder, and Polarity Flip have no upgraded or downgraded versions in-game

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#762]
Oddly enough, Hole Puncher has an _upgraded version (do 12 damage) but no changepower in its upgrade column, so there's no way to access it.

Suggestions for missing versions:
Hole Puncher-: Do 4 damage
Shredder+: Two MIN5 slots, return [] ones
Shredder-: Return 6 ones
Polarity Flip+: simplify
Polarity Flip-: complicate

(Rubber Ducky_downgraded is also the exact same as Rubber Ducky, and likewise with Rubber Ducky_weakened and Rubber Ducky_upgraded, but I figure that might be intended)

**Comment by TerryCavanagh** [comment]
Ah, thank you! Fixed all three!
