### ISSUE TITLE
Crash on game start right after character select.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#764]
`--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	halloween special / 0.13.0 (mod API)
sess. ID:	dicey_dungeons_2019-10-27_12'28'10
started:	2019-10-27 12:28:10
--------------------------------------
crashed:	2019-10-27 12:37:18
duration:	00:09:07
error:		ERROR in callscenemethod(CharacterSelect,update) static : Error: cannot find image "grid/haunted_house/haunted_houselineleft", stack = 
Called from displayobjects.HaxegonSprite.addimageframe (displayobjects/HaxegonSprite.hx line 53)
Called from displayobjects.HaxegonSprite.new (displayobjects/HaxegonSprite.hx line 37)
Called from displayobjects.DrawImage.show (displayobjects/DrawImage.hx line 80)
Called from displayobjects.OverworldGrid.addpiece (displayobjects/OverworldGrid.hx line 115)
Called from displayobjects.OverworldGrid.addpieces (displayobjects/OverworldGrid.hx line 93)
Called from displayobjects.OverworldGrid.generate (displayobjects/OverworldGrid.hx line 30)
Called from states.Dungeon.screeninit (states/Dungeon.hx line 490)
Called from states.Dungeon.descend (states/Dungeon.hx line 306)
Called from states.Episodestate.startgame (states/Episodestate.hx line 458)
Called from states.CharacterSelect.play (states/CharacterSelect.hx line 1041)
Called from FadeControl.update (FadeControl.hx line 78)
Called from Screen.endrender (Screen.hx line 277)
Called from states.CharacterSelect.update (states/CharacterSelect.hx line 303)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

`

**Comment by TerryCavanagh** [comment]
Not sure what's going on here, but there was some weirdness with the way Steam initally applied the mod when I updated this morning, and this looks like an error message that would have been caused by that (missing a resource that's definitely there). Gonna write it off as a steam glitch that's now passed - please reopen if you encounter it again!
