### ISSUE TITLE
Safety Goggles do not block Shadow Dice damage

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeonsbeta#765]
The wording on the tooltip for the Safety Goggles' status icon is "Take no damage until the end of this turn". However, you can still take damage from the health cost of using Shadow Dice to duplicate a die. Either one of these two items' associated text needs to reflect the current behavior, or the behavior should be changed to fit the text.

**Comment by TerryCavanagh** [comment]
Ah, excellent catch! Safety Goggles wasn't correctly blocking damage from piercing attacks, like Shadow Dice. Fixed now!
