### ISSUE TITLE
Swap Next Target + Curse nullifies Swap Next Target when skill successfully fires

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeonsbeta#766]
If the player has both the Swap Next Target status and the Curse status upon themself, a successfully activated skill (i.e., Curse is NOT triggered) will behave as though Swap Next Target is not in effect.

Example:
* Dire Wolf or Banshee curses player
* player uses Polarity Flip or No, You
* player successfully uses Backfire without triggering Curse
* expected behavior: enemy loses 5 health
* actual behavior: player loses 5 health

**Comment by TerryCavanagh** [comment]
Yay, thanks for this! I've figured it out, should be fixed for tomorrow!

(by the way, who are you on the beta channel?)

**Comment by findersjeepers** [comment]
Am esc!
