### ISSUE TITLE
Polarity Flip  and Pandemonium removes enemies equipment graphics but they still are able to use them 

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeonsbeta#774]
Inventor vs. Handyman. Used Polarity Flip then Pandemonium.  I received damage and Handyman had no equipment visible, but he was still able to place dice and inflict damage with his magic invisible equipment.  Also happened with "No, You" gadget.

Surprised it didn't soft lock :)

![polar](https://user-images.githubusercontent.com/40739964/67792291-49db9b00-fa4f-11e9-8802-068333cb6dd9.jpg)

**Comment by ncrecc** [comment]
Halloween is public, you don't need to use the diceydungeonsbeta repository for now

**Comment by lcenine** [comment]
Feel free to crosspost... It's kind of an edge case... Thought Terry had more important fire to put out.

**Comment by TerryCavanagh** [comment]
Fixed this for v1.6.1!
