### ISSUE TITLE
Super Enemy glow stops animating under specific conditions

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeonsbeta#80]
![super_glow_bug](https://user-images.githubusercontent.com/26709843/59034521-a06bf100-8884-11e9-8ee6-d950d1099866.gif)
Seems like it happens randomly after a fight, and always happens after opening a chest.

**Comment by TerryCavanagh** [comment]
Well spotted!

**Comment by lcenine** [comment]
This one is weird because there looks like there seems to be 3 states to super enemies, 

-Normal (pulsating glow)
-Static (as shown above)
-Pretty much absent but still a little bit of a glow around the enemy instead of the default drop shadow

**Comment by TerryCavanagh** [comment]
looks like this is fixed?
