### ISSUE TITLE
Consecutive undos produce strange behaviour with regard to statuses

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#81]
https://streamable.com/kz219

a. Normal turn: Statuses applied, followed by undo
b. Undo extraturn: Statuses applied, followed by undo
c. Undo 2nd extraturn: [bug] statuses from b. remain. End turn
d. New turn: Statuses applied, followed by undo
e. Undo extraturn: Undo
f. Undo 2nd extraturn: [bug] statuses from the end of c. are applied (!!)

**Comment by TerryCavanagh** [comment]
Technically still around, but undo is no longer a thing in vanilla, so closing!
