### ISSUE TITLE
Undo removes status icons but not tooltips, which will still appear if you hover

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#82]
https://streamable.com/0z9q4
![Screenshot 2019-06-06 at 22 59 28](https://user-images.githubusercontent.com/48322734/59069369-cb6b3a80-88ae-11e9-9a77-692b2be30ef7.png)
These remain in the background of normal tooltips for the rest of the fight

**Comment by TerryCavanagh** [comment]
No longer in the game!
