### ISSUE TITLE
Undo ignores changes to MaxHP from, eg, Kale Salad

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeonsbeta#84]
Kale Salad:
https://streamable.com/n8br4

Modded health switch:
![Screenshot 2019-06-06 at 23 16 13](https://user-images.githubusercontent.com/48322734/59070077-3e75b080-88b1-11e9-9ad3-aa1fc7e2ddd0.png)

**Comment by TerryCavanagh** [comment]
No longer in the game!
