### ISSUE TITLE
In Parallel Universe, the Pickaxe upgrade does nothing

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeonsbeta#93]
The description of Pickaxe is still min3, 1 weakness with and without the upgrade, but not displayed in the same order

**Comment by ncrecc** [comment]
1 weaken and then x damage means the weaken applies before the damage. The upgrade is essentially 1 bonus damage per use, like Dagger+ is to Dagger.

**Comment by musicalentropy** [comment]
Oh yeah you're absolutely right !
