### ISSUE TITLE
"Oh no! You've got no cards left!" after saving and loading

### ISSUE THREAD

**Issue by paceheart** [TerryCavanagh/diceydungeonsbeta#97]
Jester Elimination Round. Floor 3. Back to Title, Quit, reload, Play, Continue.

Click on Deck and oh no!

Get into a fight, Sweets pops up for a half a second in the upper left then disappears, and then oh no... I actually have no cards left.

![Dicey Dungeons Jun 13 05-19-57PM](https://user-images.githubusercontent.com/38589027/59475442-770d1100-8e00-11e9-8fd6-33d0e8c2acc8.png)

**Comment by paceheart** [comment]
[continuesave.zip](https://github.com/TerryCavanagh/diceydungeonsbeta/files/3288593/continuesave.zip)

**Comment by paceheart** [comment]
I had Shield Bash+, 2 Deflect, 3 Boop, 3 Bop, 2 Sweets, Iron Shield, maybe Duplicate... I forget what else.

**Comment by TerryCavanagh** [comment]
This one should be fixed in today's beta. Thanks!
